**GRAMMY WINNER PREDICTION**

**PROJET DALAS**

Hiba Akbi, Dwi Prima Putri


**2. SONGS FEATURE DATA SCRAPPING**

In [22]:
import bs4
import lxml
import pandas as pd
import urllib
from bs4 import BeautifulSoup
from urllib import request
import numpy as np
import re
import time

In [ ]:

!pip install beautifulsoup4


Je cree une focntion pour ecrire mes donees dans un fichier.

In [ ]:
import csv
def save_to_file(filename, header, data):
  with open(filename, mode="w", newline="") as file:
      writer = csv.writer(file)
      writer.writerow(header)
      writer.writerows(data)

In [ ]:
#fucntion to read data from a csv file. return a list of lists.
def read_file(filename):
  with open(filename, "r", newline="", encoding="utf-8") as file:
      reader = csv.reader(file)
      header=next(reader)
      data = list(reader)  # Convert to list of rows
  return header, data

The aim here is to get the unique songs that charted (because of course, we have a lot of redudant songs in the chart over the weeks).
Once we get the unique songs, we will go on to extract other features from the songs.


# Find Unique Songs from Billboard

In [ ]:
header, hot_100=read_file("bill_hot100.csv")

In [ ]:
hot_100_df= pd.DataFrame(hot_100, columns=header)

print("original data, we had: ", hot_100_df.shape[0], " song entries.")

unique_songs = hot_100_df.drop_duplicates(subset=['Title', 'Artist'], keep='first')
print("After deleting redundant songs, we have: ", unique_songs.shape[0], " unique songs.")

unique_songs= unique_songs.drop(columns=['\ufeffThe Week', 'Rank','Last Week', 'Peak Pos',
       'Weeks on Chart', 'Award'])

unique_songs

original data, we had:  135800  song entries.
After deleting redundant songs, we have:  11451  unique songs.


Title                            Artist  \
0       I Don't Want To Miss A Thing                         Aerosmith   
1                    The First Night                            Monica   
2                              Crush                    Jennifer Paige   
3                             My Way                             Usher   
4                    The Boy Is Mine                   Brandy & Monica   
...                              ...                               ...   
135760               Passport Junkie                          Rod Wave   
135773                     Talk Talk  Charli xcx Featuring Troye Sivan   
135774                    Bad Dreams                       Teddy Swims   
135794                   I Never Lie                          Zach Top   
135799                     Worst Way                       Riley Green   

                                              Song Writer  \
0                                              D.E.Warren   
1         J.Dupri Mauldin, T.Savage, M.McLeod, P.J.Sawyer   
2              A.Goldmark, M.Mueller, B.Cosgrove, K.Clark   
3            J.Dupri Mauldin, M.L.Seal, Jr., U.Raymond IV   
4       R.Jerkins, B.R.Norwood, L.A.Daniels, F.Jerkins...   
...                                                   ...   
135760  R.M.Green, T.Kozluklu, K.B.Vyacheslavovich, D....   
135773  C.E.Aitchison, A.G.Cook, R.M.Birchard, T.S.Mel...   
135774  J.C.Dimsdale, J.H.Ryan, J.C.Bunetta, M.D.Zara,...   
135794                    Z.Top, C.Chamberlain, T.Nichols   
135799                                            R.Green   

                           Producer              Label  
0                        M.Serletic           Columbia  
1                           J.Dupri             Arista  
2            A.Goldmark, J.Bralower     edel/Hollywood  
3                           J.Dupri      LaFace/Arista  
4       R.Jerkins, D.Austin, Brandy           Atlantic  
...                             ...                ...  
135760       T5, Exuising, Wonderyo              Alamo  
135773     Hudson Mohawke, A.G.Cook           Atlantic  
135774  J.H.Ryan, J.Bunetta, M.Zara  SWIMS Int./Warner  
135794                C.Chamberlain              Leo33  
135799                       D.Huff   Nashville Harbor  

[11451 rows x 5 columns]

# Split Artist and Featurings

It is a bit of an issue to look for songs using spotify API based on the song title only, instead we need the name of the main artist. In our unique_songs data, the artist column sometimes include artist featuring (ex: Fuerza Regida & Grupo Frontera) or (Santana Featuring Rob Thomas). We will do a simple split to separate between the main artist that we will keep in "Artist" column, and the secondary artists if any, that we will store in "Feat" column. We will use regex, because sometimes the splitting can be tricky. For example, we can have "A & B", "A feat. B", "A featuring B" or even when there are mutliple artists "A & B featurign C" or "A featuring B & C". We also have other variants : "A x B", "A X B", "A With B" ...etc . In any case, we are interested in the main artists only, we will then get the exact other contributers throughthe spotify API if the song is found.


In [ ]:
import numpy as np
import re

pattern = r"\s*(Feat(?:\.|uring)|&|,| X | x |Duet With|With|ft\.| And | Presents | Introducing )\s*"
keywords= ["Featuring", "Feat.", "ft.", "&", "Duet With"," With ", " X ", " x ", ",", " And ", "Presents", "Introducing"]
tests=["Busta Rhymes & Mariah Carey Featuring The Flipmode Squad","Snoop Dogg Presents Tha Eastsidaz","Young Thug And Travis Scott","Bad Bunny X Daddy Yankee","Machine Gun Kelly x Camila Cabello","Prodigy, Illa Ghee & Nina Sky", "Jagged Edge With Nelly", "Jagged Edge With Nelly","Toby Keith Duet With Willie Nelson","Drake","Baha Men With Imani Coppola", "The Roots Featuring Musiq","Fabolous Featuring Mike Shorey & Lil' Mo","Kelly Price & Friends"]
print(tests)

print([re.split(pattern, test, maxsplit=1)[0] if any(keyword in test for keyword in keywords) else test for test in tests ])
print([re.split(pattern, test, maxsplit=1)[2] if any(keyword in test for keyword in keywords) else None for test in tests ])

artist= [re.split(pattern, value, maxsplit=1)[0].strip() if any(k in value for k in keywords) else value for value in unique_songs["Artist"] ]
feats= [re.split(pattern, value, maxsplit=1)[2].strip() if any(k in value for k in keywords) else None for value in unique_songs["Artist"] ]


unique_songs.insert(2, "Main Artist", artist)
unique_songs.insert(3, "Feat", feats)


unique_songs


['Busta Rhymes & Mariah Carey Featuring The Flipmode Squad', 'Snoop Dogg Presents Tha Eastsidaz', 'Young Thug And Travis Scott', 'Bad Bunny X Daddy Yankee', 'Machine Gun Kelly x Camila Cabello', 'Prodigy, Illa Ghee & Nina Sky', 'Jagged Edge With Nelly', 'Jagged Edge With Nelly', 'Toby Keith Duet With Willie Nelson', 'Drake', 'Baha Men With Imani Coppola', 'The Roots Featuring Musiq', "Fabolous Featuring Mike Shorey & Lil' Mo", 'Kelly Price & Friends']
['Busta Rhymes', 'Snoop Dogg', 'Young Thug', 'Bad Bunny', 'Machine Gun Kelly', 'Prodigy', 'Jagged Edge', 'Jagged Edge', 'Toby Keith', 'Drake', 'Baha Men', 'The Roots', 'Fabolous', 'Kelly Price']
['Mariah Carey Featuring The Flipmode Squad', 'Tha Eastsidaz', 'Travis Scott', 'Daddy Yankee', 'Camila Cabello', 'Illa Ghee & Nina Sky', 'Nelly', 'Nelly', 'Willie Nelson', None, 'Imani Coppola', 'Musiq', "Mike Shorey & Lil' Mo", 'Friends']


NameError: name 'unique_songs' is not defined

In [ ]:
unique_songs.iloc[0]

Title          I Don't Want To Miss A Thing
Artist                            Aerosmith
Main Artist                       Aerosmith
Feat                                   None
Song Writer                      D.E.Warren
Producer                         M.Serletic
Label                              Columbia
Name: 0, dtype: object

Seems like we are ready now to get some data from spotify API. We are mainly interested in 2 infos:

*  The **Album** the song belongs to
*  The **duration** of the song in seconds.
*  A cleaner version of the **Featured Artists**. Mainly because spotify will include the featured artists, while billboard seem to include all contributing artists.



In [3]:
!pip install spotipy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 261.5/261.5 kB 6.4 MB/s eta 0:00:00


In [9]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

# Set up Spotify API credentials
client_id = 'baa1b7896aad4ebabdf13a12fb7da44a'  # Replace with your actual Client ID
client_secret = '451d7b1751274ec9ba0285144a99290f'  # Replace with your actual Client Secret

# Authenticate with Spotify API
client_credentials_manager = SpotifyClientCredentials(client_id=client_id, client_secret=client_secret)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

In [ ]:
import time
album=[]
duration=[]
feats=[]
found=[]
i=0
for idx, row in unique_songs.iterrows():
  i+=1
  # if i>=4783:
  print(i)
  song_name = row["Title"]
  artist_name=row["Main Artist"]
  results = sp.search(q=f"track:{song_name} artist:{artist_name}", limit=1, type='track')
  if idx%2==0: time.sleep(0.2) #to avoid too many request per second
  Flag=1
  # Extract relevant details
  if(len(results['tracks']['items'])==0):
    print("Song not found", row )

    print("-"*10)
    Flag=0
  else: track = results['tracks']['items'][0]

  found.append(Flag) #0 if not found else 1
  album.append(track['album']['name'] if Flag else None)
  duration.append(track['duration_ms']/1000 if Flag else None)
  if Flag:
    all_artists=[artist["name"] for artist in track["artists"]]
    if len(all_artists)==1: feats.append(None) #if theres only one artist, then there is no feat
    else: feats.append(','.join(all_artists[1:])) #store the feats only, not the main artist
  else: feats.append(None)


Streaming output truncated to the last 5000 lines.
7028
7029
7030
7031
7032
7033
7034
7035
7036
7037
7038
7039
7040
7041
7042
7043
7044
7045
7046
7047
7048
7049
7050
7051
7052
7053
7054
7055
7056
7057
7058
7059
Song not found Title          Ghost In This House
Artist                Lauren Duski
Main Artist           Lauren Duski
Feat                          None
Song Writer            H.Prestwood
Producer              B.Appleberry
Label                     Republic
Name: 97597, dtype: object
----------
7060
7061
7062
Song not found Title                                        Deja Vu
Artist                                  Lauren Duski
Main Artist                             Lauren Duski
Feat                                            None
Song Writer    D.C.Tarpley Jr., L.E.Duski, D.D.Henig
Producer                                Cody Tarpley
Label                                       Republic
Name: 97642, dtype: object
----------
7063
7064
7065
Song not found Title                 

In [ ]:
print(len(found))

11451


Our initial run through spotify API with only cleaning the artist name seems quite succesful. We have only 331 missing songs.

In [ ]:
mask=(np.array(found)==0)
filtered_not_found=unique_songs.loc[mask]
print("We have ", len(filtered_not_found), " songs not found out of ", len(unique_songs))

We have  331  songs not found out of  11451


In [ ]:
newdf = unique_songs.copy() #copy to keep this version in case of anything
newdf["Album"]=album
newdf["Duration"]=duration
newdf["Featured Artists"]=feats
newdf["Spotify Found"]=found
newdf

Title                            Artist  \
0       I Don't Want To Miss A Thing                         Aerosmith   
1                    The First Night                            Monica   
2                              Crush                    Jennifer Paige   
3                             My Way                             Usher   
4                    The Boy Is Mine                   Brandy & Monica   
...                              ...                               ...   
135760               Passport Junkie                          Rod Wave   
135773                     Talk Talk  Charli xcx Featuring Troye Sivan   
135774                    Bad Dreams                       Teddy Swims   
135794                   I Never Lie                          Zach Top   
135799                     Worst Way                       Riley Green   

           Main Artist         Feat  \
0            Aerosmith         None   
1               Monica         None   
2       Jennifer Paige         None   
3                Usher         None   
4               Brandy       Monica   
...                ...          ...   
135760        Rod Wave         None   
135773      Charli xcx  Troye Sivan   
135774     Teddy Swims         None   
135794        Zach Top         None   
135799     Riley Green         None   

                                              Song Writer  \
0                                              D.E.Warren   
1         J.Dupri Mauldin, T.Savage, M.McLeod, P.J.Sawyer   
2              A.Goldmark, M.Mueller, B.Cosgrove, K.Clark   
3            J.Dupri Mauldin, M.L.Seal, Jr., U.Raymond IV   
4       R.Jerkins, B.R.Norwood, L.A.Daniels, F.Jerkins...   
...                                                   ...   
135760  R.M.Green, T.Kozluklu, K.B.Vyacheslavovich, D....   
135773  C.E.Aitchison, A.G.Cook, R.M.Birchard, T.S.Mel...   
135774  J.C.Dimsdale, J.H.Ryan, J.C.Bunetta, M.D.Zara,...   
135794                    Z.Top, C.Chamberlain, T.Nichols   
135799                                            R.Green   

                           Producer              Label  \
0                        M.Serletic           Columbia   
1                           J.Dupri             Arista   
2            A.Goldmark, J.Bralower     edel/Hollywood   
3                           J.Dupri      LaFace/Arista   
4       R.Jerkins, D.Austin, Brandy           Atlantic   
...                             ...                ...   
135760       T5, Exuising, Wonderyo              Alamo   
135773     Hudson Mohawke, A.G.Cook           Atlantic   
135774  J.H.Ryan, J.Bunetta, M.Zara  SWIMS Int./Warner   
135794                C.Chamberlain              Leo33   
135799                       D.Huff   Nashville Harbor   

                                                    Album  Duration  \
0                         I Don't Want To Miss A Thing EP   299.723   
1                                         The Boy Is Mine   235.573   
2                                          Jennifer Paige   200.293   
3                                                  My Way   214.853   
4                                 the boy is mine (Remix)   213.384   
...                                                   ...       ...   
135760                                           Last Lap   147.749   
135773  Brat and it’s completely different but also st...   173.076   
135774                                         Bad Dreams   184.577   
135794                          Cold Beer & Country Music   224.906   
135799                                       Way Out Here   220.558   

       Featured Artists  Spotify Found  
0                  None              1  
1                  None              1  
2                  None              1  
3                  None              1  
4         Brandy,Monica              1  
...                 ...            ...  
135760             None              1  
135773      Troye Sivan              1  
135774             No

Now, we store our unique songs with the additional data we got from spotify in a csv file. Later, we will just import this file to continue our preprocessign to avoid the excessive Spotify API calls for each data loading.

In [ ]:
newdf.to_csv('unique_songs.csv', index=True) #index is holding the ID of the row in the original billbaord data
header, single_songs=read_file("unique_songs.csv")
header=['Song ID', 'Title', 'Artist', 'Main Artist', 'Feat', 'Song Writers/Credits', 'Producer', 'Label', 'Album', 'Duration', 'Spotify Featured Artists', 'Spotify Found']
single_songs_df= pd.DataFrame(single_songs, columns=header)
single_songs_df.to_csv('single_songs.csv', index=False) #fix the name of columns and save it again


**Only piece of code to run for next time**

In [ ]:
header, single_songs=read_file("single_songs.csv")
single_songs_df= pd.DataFrame(single_songs, columns=header)
single_songs_df #11451 x 12

Song ID                         Title                            Artist  \
0           0  I Don't Want To Miss A Thing                         Aerosmith   
1           1               The First Night                            Monica   
2           2                         Crush                    Jennifer Paige   
3           3                        My Way                             Usher   
4           4               The Boy Is Mine                   Brandy & Monica   
...       ...                           ...                               ...   
11446  135760               Passport Junkie                          Rod Wave   
11447  135773                     Talk Talk  Charli xcx Featuring Troye Sivan   
11448  135774                    Bad Dreams                       Teddy Swims   
11449  135794                   I Never Lie                          Zach Top   
11450  135799                     Worst Way                       Riley Green   

          Main Artist         Feat  \
0           Aerosmith                
1              Monica                
2      Jennifer Paige                
3               Usher                
4              Brandy       Monica   
...               ...          ...   
11446        Rod Wave                
11447      Charli xcx  Troye Sivan   
11448     Teddy Swims                
11449        Zach Top                
11450     Riley Green                

                                    Song Writers/Credits  \
0                                             D.E.Warren   
1        J.Dupri Mauldin, T.Savage, M.McLeod, P.J.Sawyer   
2             A.Goldmark, M.Mueller, B.Cosgrove, K.Clark   
3           J.Dupri Mauldin, M.L.Seal, Jr., U.Raymond IV   
4      R.Jerkins, B.R.Norwood, L.A.Daniels, F.Jerkins...   
...                                                  ...   
11446  R.M.Green, T.Kozluklu, K.B.Vyacheslavovich, D....   
11447  C.E.Aitchison, A.G.Cook, R.M.Birchard, T.S.Mel...   
11448  J.C.Dimsdale, J.H.Ryan, J.C.Bunetta, M.D.Zara,...   
11449                    Z.Top, C.Chamberlain, T.Nichols   
11450                                            R.Green   

                          Producer              Label  \
0                       M.Serletic           Columbia   
1                          J.Dupri             Arista   
2           A.Goldmark, J.Bralower     edel/Hollywood   
3                          J.Dupri      LaFace/Arista   
4      R.Jerkins, D.Austin, Brandy           Atlantic   
...                            ...                ...   
11446       T5, Exuising, Wonderyo              Alamo   
11447     Hudson Mohawke, A.G.Cook           Atlantic   
11448  J.H.Ryan, J.Bunetta, M.Zara  SWIMS Int./Warner   
11449                C.Chamberlain              Leo33   
11450                       D.Huff   Nashville Harbor   

                                                   Album Duration  \
0                        I Don't Want To Miss A Thing EP  299.723   
1                                        The Boy Is Mine  235.573   
2                                         Jennifer Paige  200.293   
3                                                 My Way  214.853   
4                                the boy is mine (Remix)  213.384   
...                                                  ...      ...   
11446                                           Last Lap  147.749   
11447  Brat and it’s completely different but also st...  173.076   
11448                                         Bad Dreams  184.577   
11449                          Cold Beer & Country Music  224.906   
11450                                       Way Out Here  220.558   

      Spotify Featured Artists Spotify Found  
0                                          1  
1                                          1  
2                                          1  
3                                          1  
4                Brandy,Monica             1  
...                        ...           ...  
11446       


This block of code is just meant to just organzie all of these by idx so that our data remains trackable. So I will assign to each unique song a unique ID (which is its index in the original billbaord data), and I will give the same ID to all its duplicates. This way it will be easy to draw charts on a single song over time. And also merge different tables based on unqiue song ID.


So now, the songs in "hot_100_idx.csv" which is the billbaord data (that contains many duplicates for the same song), and the songs in "unique_songs.csv" can be joined by the column "Song_ID". This will help us later especially for visualization.

In [ ]:
og_df= hot_100_df.copy()
hot_100_idx = og_df.merge(single_songs_df[['Title', 'Artist', 'Song ID']], on=['Title', 'Artist'], how='left')
cols = ['Song ID'] + [col for col in hot_100_idx.columns if col != 'Song ID']
hot_100_idx = hot_100_idx[cols]

# print(hot_100_idx.columns)

hot_100_idx.to_csv('hot_100_idx.csv')

# Data Cleaning to improve Spotify Search

By taking a look at the missing data we have, we notice the following:
* Some songs might not have been found because of **uncleaned details in their title**. For example: Obsession (No Es Amor) having parenthesis for the alternative title. It's worth trying to clean the data that wasn't found to see if the songs name get recognized with only part of the title. There's also a pattern with **swear words** not being recognized, and words containing the **$** sign.

* Some songs weren't recngonized because of the artist name. For exmaple many songs appearing as **"¥$: Kanye West"** would probably be found in the spotify catalog as "Kanye West"


* Some songs with clean titles and artist name might not have been recognized simply because they don not exist in the Spotify Catalog.


Therefore, we will proceed to a little bit more data proprocessing.

* First to handle swear words, we will have a small dictionary of swear words and reconstruct "F*uck" into "Fuck".

* We will manually handle the issue of "Ye". And we will replace the dollar signs by an S isntead.

Lets' run a small tets to tets our hypothesis on songs that were not found earlier.



In [ ]:
test_songs=["All These Niggas", "Give Me A Sign", "Promotion", "Never Too Far" , "Ransom"]
test_artists=["King Von", "Breaking Benjamin", "Kanye West", "Mariah Carey", "Lil Tecca"]

for song_name, artist_name in zip(test_songs, test_artists):
  results = sp.search(q=f"track:{song_name} artist:{artist_name}", limit=1, type='track')
  # Extract relevant details
  if(len(results['tracks']['items'])==0):
    print("Song not found ", song_name, "\t", artist_name )

  else : print("Yay song was found now")

Yay song was found now
Yay song was found now
Yay song was found now
Yay song was found now
Yay song was found now


Seems like the preprocessing is working great, so we apply it.
We will put the cleaned data in a newdf.

# Profanity Decoder
First we build our profanity decoder.
I take a firts look at the type of swear words we have in the title.

In [ ]:
#get all profanities (they contain *)
profanities=[row['Title'] for idx, row in single_songs_df.iterrows() if row['Spotify Found']=='0' and '*' in row['Title'] ]
print(profanities)

['From Her Mama (Mama Got A**)', 'P***ycat', 'Shake That Sh**', "Bitches Ain't S**t", 'Love Me Or Hate Me (F**k You!!!!)', 'J**z In My Pants', 'F*ck You', 'F**k Today', 'F**k You! (Forget You)', 'HYFR (Hell Ya F*****g Right)', 'Rich As F**k', 'F**k That Check Up', 'Dope N****z', 'All These N**gas', 'Constant Bulls**t', 'Switch A N*gga Out', "I'm Dat N***a", 'F**k The Industry Pt. 2']


Looks like we have a small vocabulary of words, the issue is with the different ways that * are placed (B\*tch, B\*\*\*h, B\*\*\*\* ...etc), and variations in the word like plural and singular and -ing. This can be easily solved by matching with 'IN' instead of an exact match of the word.

In [ ]:
profanity_dict={
    "mutha*****": "muthafucka",
    "f*ck": "fuck",
    "f***":"fuck",
    "f**k": "fuck",
    "n**kin":"fuckin",
    "f*****g":"fucking",
    "fuck**g":"fucking",
    "s**t": "shit",
    "sh*t": "shit",
    "sh**":"shit",
    "d@mn": "damn",
    "d*mn": "damn",
    "h*ll": "hell",
    "b*****s":"bitches",
    "b****":"bitch",
    "b*tch": "bitch",
    "b**ch": "bitch",
    "b**tch":"bitch",
    "b***h":"bitch",
    "a**": "ass",
    "p*ssy":"pussy",
    "p***y":"pussy",
    "p****":"pussy",
    "n****":"nigga",
    "n***a":"nigga",
    "n**ga":"nigga",
    "n*gga":"nigga",
    "ni**a":"nigga",
    "j**z": "jizz",

}

#decode profanity : (F*ck -> fuck)
def decode_profanity(title):
  for key,value in profanity_dict.items():
    # print(key in title.lower(), key,"----------", title.lower())
    if key in title.lower():
      title=title.lower()
      title=title.replace(key,value)
  return title

In [ ]:
# tets profanities
no_prof=[decode_profanity(t) for t in profanities]
print(profanities)
print(no_prof)

['From Her Mama (Mama Got A**)', 'P***ycat', 'Shake That Sh**', "Bitches Ain't S**t", 'Love Me Or Hate Me (F**k You!!!!)', 'J**z In My Pants', 'F*ck You', 'F**k Today', 'F**k You! (Forget You)', 'HYFR (Hell Ya F*****g Right)', 'Rich As F**k', 'F**k That Check Up', 'Dope N****z', 'All These N**gas', 'Constant Bulls**t', 'Switch A N*gga Out', "I'm Dat N***a", 'F**k The Industry Pt. 2']
['from her mama (mama got ass)', 'pussycat', 'shake that shit', "bitches ain't shit", 'love me or hate me (fuck you!!!!)', 'jizz in my pants', 'fuck you', 'fuck today', 'fuck you! (forget you)', 'hyfr (hell ya fucking right)', 'rich as fuck', 'fuck that check up', 'dope niggaz', 'all these niggas', 'constant bullshit', 'switch a nigga out', "i'm dat nigga", 'fuck the industry pt. 2']


Looks like ou profanity decoder is working, so now we can proceed to other types of title preprocessing. We got to handle the parenthesis in titles, and cases when the songs has two titles (generally written as Title/Altternative_Title).

We also want to handle the case of the \$ that is recognized by making it S.

In [ ]:
#delete whats in parenthesis : Title(Alt. Title) -> Title
def clean_parenthesis(title):
  parenthesis_pattern= r"\(.*?\)"
  title=re.split(parenthesis_pattern, title,maxsplit=1)
  title=" ".join(title)
  return title.strip()


def preprocess_title(title):
  res=title
  if (",") in res: res=res.replace(',', " ") #handle the commas in a title
  if (".") in res: res=re.sub(r"(?<!\d)\.(?!\d)", " ", res) #handle the dots in a title unless its part of a number
  if ("$") in res: res=res.replace('$','s') #handle $
  if ("(") in res: res=clean_parenthesis(res)
  if ("/") in res: res=res.split("/")[0]
  if ("*") in res: res=decode_profanity(res)
  res=re.sub(r" +", " ", res) #replace any adidtional spaces that we created into a single space
  return res.strip()



In [ ]:
titles_not_found=[row['Title'] for idx, row in single_songs_df.iterrows() if row['Spotify Found']=='0' and '(' in row['Title'] or '$' in row['Title'] ]
titles_cleaned=[preprocess_title(t) for t in titles_not_found ]

print(titles_not_found)
print(titles_cleaned)

['SuperThug (What What)', "Everybody's Free (To Wear Sunscreen)", 'The Christmas Song (Chestnuts Roasting On An Open Fire)', "I'll Fly With You (L'amour Toujours)", 'From Her Mama (Mama Got A**)', "Young'n (Holla Back)", 'Rapture (Tastes So Sweet)', "Tell Me (What's Goin' On)", 'Roll Wit M.V.P. (We Be Like! The La La Song)', 'Simply Being Loved (Somnambulist)', 'Sympathy For The Devil (Remixes)', 'Another Postcard (Chimps)', 'Work It (Reinvention)', 'Obsession (No Es Amor)', 'Helena (So Long & Goodnight)', 'Stay With Me (Brass Bed)', "Kryptonite (I'm On It)", "Oh Yes (aka 'Postman')", "What I've Been Looking For (Reprise)", 'For You I Will (Confidence)', 'Love Me Or Hate Me (F**k You!!!!)', "I'll Be Home For Christmas (Live)", 'The Story (I Was Made For You)', 'Do You Know? (The Ping Pong Song)/Dimelo', "The Chipmunk Song (Christmas Don't Be Late) (2007)", 'Witch Doctor (2007)', 'Leave It All To Me (iCarly Theme Song)', 'Check Yes Juliet (Run Baby Run)', 'Pen & Paper (Something Typical

Seems like our title preprocessing is workign great. Let's apply in a new column called "Cleaned_titles". We're gonna keep it in a seperate column and apply it on all rows (whether they were found in Spotify or not), this is so that the preprocessing can be used for other APIs later.

In [ ]:
clean_single_songs_df=single_songs_df.copy() #keep a copy
cleaned_titles = clean_single_songs_df["Title"].apply(lambda x: preprocess_title(x))
clean_single_songs_df.insert(loc=2, column='Cleaned Title', value=cleaned_titles)
clean_single_songs_df #11451x13

Song ID                         Title                 Cleaned Title  \
0           0  I Don't Want To Miss A Thing  I Don't Want To Miss A Thing   
1           1               The First Night               The First Night   
2           2                         Crush                         Crush   
3           3                        My Way                        My Way   
4           4               The Boy Is Mine               The Boy Is Mine   
...       ...                           ...                           ...   
11446  135760               Passport Junkie               Passport Junkie   
11447  135773                     Talk Talk                     Talk Talk   
11448  135774                    Bad Dreams                    Bad Dreams   
11449  135794                   I Never Lie                   I Never Lie   
11450  135799                     Worst Way                     Worst Way   

                                 Artist     Main Artist         Feat  \
0                             Aerosmith       Aerosmith                
1                                Monica          Monica                
2                        Jennifer Paige  Jennifer Paige                
3                                 Usher           Usher                
4                       Brandy & Monica          Brandy       Monica   
...                                 ...             ...          ...   
11446                          Rod Wave        Rod Wave                
11447  Charli xcx Featuring Troye Sivan      Charli xcx  Troye Sivan   
11448                       Teddy Swims     Teddy Swims                
11449                          Zach Top        Zach Top                
11450                       Riley Green     Riley Green                

                                    Song Writers/Credits  \
0                                             D.E.Warren   
1        J.Dupri Mauldin, T.Savage, M.McLeod, P.J.Sawyer   
2             A.Goldmark, M.Mueller, B.Cosgrove, K.Clark   
3           J.Dupri Mauldin, M.L.Seal, Jr., U.Raymond IV   
4      R.Jerkins, B.R.Norwood, L.A.Daniels, F.Jerkins...   
...                                                  ...   
11446  R.M.Green, T.Kozluklu, K.B.Vyacheslavovich, D....   
11447  C.E.Aitchison, A.G.Cook, R.M.Birchard, T.S.Mel...   
11448  J.C.Dimsdale, J.H.Ryan, J.C.Bunetta, M.D.Zara,...   
11449                    Z.Top, C.Chamberlain, T.Nichols   
11450                                            R.Green   

                          Producer              Label  \
0                       M.Serletic           Columbia   
1                          J.Dupri             Arista   
2           A.Goldmark, J.Bralower     edel/Hollywood   
3                          J.Dupri      LaFace/Arista   
4      R.Jerkins, D.Austin, Brandy           Atlantic   
...                            ...                ...   
11446       T5, Exuising, Wonderyo              Alamo   
11447     Hudson Mohawke, A.G.Cook           Atlantic   
11448  J.H.Ryan, J.Bunetta, M.Zara  SWIMS Int./Warner   
11449                C.Chamberlain              Leo33   
11450                       D.Huff   Nashville Harbor   

                                                   Album Duration  \
0                        I Don't Want To Miss A Thing EP  299.723   
1                                        The Boy Is Mine  235.573   
2                                         Jennifer Paige  200.293   
3                                                 My Way  214.853   
4                                the boy is mine (Remix)  213.384   
...                                                  ...      ...   
11446                                           Last Lap  147.749   
11447  Brat and it’s completely different but also st...  173.076   
11448                                         Bad Dreams  184.577   
11449                          Cold Beer & Country Music  224.906   
11450                                       Way Out

Perefct, seems like the only remaining titles with * aren't porfanities anyway. So we succesfully decoded all our profanities.

In [ ]:
#after preprocessing
#get all profanities (they contain *)
profanities=[row['Cleaned Title'] for idx, row in clean_single_songs_df.iterrows() if '*' in row['Cleaned Title'] ]
print(profanities)

['H*A*M', '***Flawless', 'Wokeuplikethis*', "Sweet * Honey * Buckiin'"]


Now that the titles are clean, let's proceed to cleanign the artist name.
We have to clean the $ and the issue with Kanye West. Let's see if there's anythign else to clean in terms of artist names.


In [ ]:

unclean_artists=[row['Main Artist'] for idx, row in clean_single_songs_df.iterrows() if row['Spotify Found']=='0' and '*' not in row['Title'] and '(' not in row['Title'] ]
print(unclean_artists)

['Puff Daddy', 'Debelah Morgan', 'Stars On 54: Ultra Nate', 'Pure Sugar', "J'Son", 'Funkmaster Flex', 'Tragedy', 'Tami Davis', 'Missjones', 'Mag 7', 'BRAVO All Stars', 'L.F.O. (Lyte Funky Ones)', 'Tami Davis', 'Randy Travis', 'Silkk The Shocker', 'Divine', 'Randy Travis', 'Youngstown', 'Erykah Badu', 'Garth Brooks as Chris Gaines', 'Randy Travis', 'The Lox', 'Dave Hollister', 'Snoop Dogg', 'Jay-Z', 'Damizza', 'Cash Money Millionaires', 'Mr. C The Slide Man', 'Aaron Lewis Of Staind', 'Iconz', 'Monica', 'Sarina Paris', 'Tim Rushlow', 'Jimmy Cozier', 'Carolyn Dawn Johnson', 'Ludacris', 'Master P', 'Mariah Carey', 'R. Kelly', 'Brian McKnight', 'Jade Anderson', 'Irv Gotti', 'Soluna', 'Yasmeen', 'Tim McGraw', 'Common', 'Rascal Flatts', 'American Idol Finalists', 'Lumidee', 'Kiley Dean', 'M.V.P. (Most Valuable Playas)', 'Scotty Emerick', 'Ryan Duarte', 'Obie Trice', 'Joe Nichols', 'Anita Baker', 'Christina Aguilera', 'R. Kelly', 'Melissa Etheridge', 'American Idol Finalists Season 4', 'Bobby 

This seems  abit more problematic. It seems that for most of the names, they are valid artist names.
It wouldn't make sense to delete numbers and punctuation from artists' names because they wouldn't be recognized otherwise (6ix9ine would become ixine).
Also, there are quite famous artist names in there, so the songs not being found probably has to do with Spotify not having the song in their catalog rather than an issue with the name of the artist.

So we will just stick to our intial hypothesis and clean Ye and $, as well as the parenthesis.

In [ ]:
#preprcoessing on artist names
#replace kanye west name
mask_ye= (clean_single_songs_df["Spotify Found"]=='0') & (clean_single_songs_df["Main Artist"].str.contains("¥\$", na=False))
clean_single_songs_df.loc[mask_ye, "Main Artist"] = "Kanye West"
clean_single_songs_df

Song ID                         Title                 Cleaned Title  \
0           0  I Don't Want To Miss A Thing  I Don't Want To Miss A Thing   
1           1               The First Night               The First Night   
2           2                         Crush                         Crush   
3           3                        My Way                        My Way   
4           4               The Boy Is Mine               The Boy Is Mine   
...       ...                           ...                           ...   
11446  135760               Passport Junkie               Passport Junkie   
11447  135773                     Talk Talk                     Talk Talk   
11448  135774                    Bad Dreams                    Bad Dreams   
11449  135794                   I Never Lie                   I Never Lie   
11450  135799                     Worst Way                     Worst Way   

                                 Artist     Main Artist         Feat  \
0                             Aerosmith       Aerosmith                
1                                Monica          Monica                
2                        Jennifer Paige  Jennifer Paige                
3                                 Usher           Usher                
4                       Brandy & Monica          Brandy       Monica   
...                                 ...             ...          ...   
11446                          Rod Wave        Rod Wave                
11447  Charli xcx Featuring Troye Sivan      Charli xcx  Troye Sivan   
11448                       Teddy Swims     Teddy Swims                
11449                          Zach Top        Zach Top                
11450                       Riley Green     Riley Green                

                                    Song Writers/Credits  \
0                                             D.E.Warren   
1        J.Dupri Mauldin, T.Savage, M.McLeod, P.J.Sawyer   
2             A.Goldmark, M.Mueller, B.Cosgrove, K.Clark   
3           J.Dupri Mauldin, M.L.Seal, Jr., U.Raymond IV   
4      R.Jerkins, B.R.Norwood, L.A.Daniels, F.Jerkins...   
...                                                  ...   
11446  R.M.Green, T.Kozluklu, K.B.Vyacheslavovich, D....   
11447  C.E.Aitchison, A.G.Cook, R.M.Birchard, T.S.Mel...   
11448  J.C.Dimsdale, J.H.Ryan, J.C.Bunetta, M.D.Zara,...   
11449                    Z.Top, C.Chamberlain, T.Nichols   
11450                                            R.Green   

                          Producer              Label  \
0                       M.Serletic           Columbia   
1                          J.Dupri             Arista   
2           A.Goldmark, J.Bralower     edel/Hollywood   
3                          J.Dupri      LaFace/Arista   
4      R.Jerkins, D.Austin, Brandy           Atlantic   
...                            ...                ...   
11446       T5, Exuising, Wonderyo              Alamo   
11447     Hudson Mohawke, A.G.Cook           Atlantic   
11448  J.H.Ryan, J.Bunetta, M.Zara  SWIMS Int./Warner   
11449                C.Chamberlain              Leo33   
11450                       D.Huff   Nashville Harbor   

                                                   Album Duration  \
0                        I Don't Want To Miss A Thing EP  299.723   
1                                        The Boy Is Mine  235.573   
2                                         Jennifer Paige  200.293   
3                                                 My Way  214.853   
4                                the boy is mine (Remix)  213.384   
...                                                  ...      ...   
11446                                           Last Lap  147.749   
11447  Brat and it’s completely different but also st...  173.076   
11448                                         Bad Dreams  184.577   
11449                          Cold Beer & Country Music  224.906   
11450                                       Way Out

In [ ]:
#fix the $ issue
mask=(clean_single_songs_df["Spotify Found"]=='0') & (clean_single_songs_df["Main Artist"].str.contains(r'\$', na=False))
clean_single_songs_df.loc[mask, "Main Artist"] = clean_single_songs_df.loc[mask, "Main Artist"].replace(r'\$', 's', regex=True)


In [ ]:
#here im fixing this becasue i missed it earlier , some stuff relaing to splitting artist names
mask=(clean_single_songs_df["Spotify Found"]=='0') & (clean_single_songs_df["Main Artist"].str.contains(r'R\. Kelly Or Bow Wow \(', na=False))
clean_single_songs_df.loc[mask, "Main Artist"] = "Bow Wow"

mask= (clean_single_songs_df["Main Artist"].str.contains(r' \+ ', na=False))
clean_single_songs_df.loc[mask, "Main Artist"] = clean_single_songs_df.loc[mask, "Main Artist"].str.split(r" \+ ").str[0]

mask= (clean_single_songs_df["Main Artist"].str.contains(" Co-Starring ", na=False))
clean_single_songs_df.loc[mask, "Main Artist"] = clean_single_songs_df.loc[mask, "Main Artist"].str.split(r" Co-Starring ").str[0]


mask= (clean_single_songs_df["Main Artist"].str.lower().str.contains("vs.?", na=False))
clean_single_songs_df.loc[mask, "Main Artist"] = clean_single_songs_df.loc[mask, "Main Artist"].str.lower().str.split(r"vs.?").str[0].str.title()

mask= (clean_single_songs_df["Main Artist"].str.contains(r'/', na=False))
clean_single_songs_df.loc[mask, "Main Artist"] = clean_single_songs_df.loc[mask, "Main Artist"].str.split("/").str[0]

In [ ]:
mask=(clean_single_songs_df["Main Artist"].str.contains(r'Silk Sonic \(', na=False))
clean_single_songs_df.loc[mask, "Main Artist"] = "Silk Sonic"


mask=((clean_single_songs_df["Main Artist"].str.contains(r'\(', na=False)) & (~clean_single_songs_df["Main Artist"].str.contains(r'\)', na=False)))
clean_single_songs_df.loc[mask, "Main Artist"] =  clean_single_songs_df.loc[mask, "Main Artist"].str.split("\(").str[0]



In [ ]:
clean_single_songs_df

Song ID                         Title                 Cleaned Title  \
0           0  I Don't Want To Miss A Thing  I Don't Want To Miss A Thing   
1           1               The First Night               The First Night   
2           2                         Crush                         Crush   
3           3                        My Way                        My Way   
4           4               The Boy Is Mine               The Boy Is Mine   
...       ...                           ...                           ...   
11446  135760               Passport Junkie               Passport Junkie   
11447  135773                     Talk Talk                     Talk Talk   
11448  135774                    Bad Dreams                    Bad Dreams   
11449  135794                   I Never Lie                   I Never Lie   
11450  135799                     Worst Way                     Worst Way   

                                 Artist     Main Artist         Feat  \
0                             Aerosmith       Aerosmith                
1                                Monica          Monica                
2                        Jennifer Paige  Jennifer Paige                
3                                 Usher           Usher                
4                       Brandy & Monica          Brandy       Monica   
...                                 ...             ...          ...   
11446                          Rod Wave        Rod Wave                
11447  Charli xcx Featuring Troye Sivan      Charli xcx  Troye Sivan   
11448                       Teddy Swims     Teddy Swims                
11449                          Zach Top        Zach Top                
11450                       Riley Green     Riley Green                

                                    Song Writers/Credits  \
0                                             D.E.Warren   
1        J.Dupri Mauldin, T.Savage, M.McLeod, P.J.Sawyer   
2             A.Goldmark, M.Mueller, B.Cosgrove, K.Clark   
3           J.Dupri Mauldin, M.L.Seal, Jr., U.Raymond IV   
4      R.Jerkins, B.R.Norwood, L.A.Daniels, F.Jerkins...   
...                                                  ...   
11446  R.M.Green, T.Kozluklu, K.B.Vyacheslavovich, D....   
11447  C.E.Aitchison, A.G.Cook, R.M.Birchard, T.S.Mel...   
11448  J.C.Dimsdale, J.H.Ryan, J.C.Bunetta, M.D.Zara,...   
11449                    Z.Top, C.Chamberlain, T.Nichols   
11450                                            R.Green   

                          Producer              Label  \
0                       M.Serletic           Columbia   
1                          J.Dupri             Arista   
2           A.Goldmark, J.Bralower     edel/Hollywood   
3                          J.Dupri      LaFace/Arista   
4      R.Jerkins, D.Austin, Brandy           Atlantic   
...                            ...                ...   
11446       T5, Exuising, Wonderyo              Alamo   
11447     Hudson Mohawke, A.G.Cook           Atlantic   
11448  J.H.Ryan, J.Bunetta, M.Zara  SWIMS Int./Warner   
11449                C.Chamberlain              Leo33   
11450                       D.Huff   Nashville Harbor   

                                                   Album Duration  \
0                        I Don't Want To Miss A Thing EP  299.723   
1                                        The Boy Is Mine  235.573   
2                                         Jennifer Paige  200.293   
3                                                 My Way  214.853   
4                                the boy is mine (Remix)  213.384   
...                                                  ...      ...   
11446                                           Last Lap  147.749   
11447  Brat and it’s completely different but also st...  173.076   
11448                                         Bad Dreams  184.577   
11449                          Cold Beer & Country Music  224.906   
11450                                       Way Out

In [ ]:
#same code as earlier, just now we are working with the cleaned data and also working with only rows that weren't previously found.
i=0
for idx, row in clean_single_songs_df.iterrows():
  if row["Spotify Found"]=='0':
    song_name = row["Cleaned Title"]
    artist_name=row["Main Artist"]
    results = sp.search(q=f"track:{song_name} artist:{artist_name}", limit=1, type='track')
    if idx%2==0: time.sleep(0.2) #to avoid too many request per second
    Flag=1
    # Extract relevant details
    if(len(results['tracks']['items'])==0):
      i+=1
      print("Song not found", row )
      print("-"*10)
      Flag=0
    else: track = results['tracks']['items'][0]

    clean_single_songs_df.loc[idx, "Spotify Found"]= Flag #update the flag
    if Flag:
      clean_single_songs_df.loc[idx, "Album"]=track['album']['name']
      clean_single_songs_df.loc[idx, "Duration"]=track['duration_ms']/1000
      all_artists=[artist["name"] for artist in track["artists"]]
      if len(all_artists)!=1: clean_single_songs_df.loc[idx, "Spotify Featured Artists"]=None #if theres only one artist, then there is no feat
      else: clean_single_songs_df.loc[idx, "Spotify Featured Artists"]=','.join(all_artists[1:]) #store the feats only, not the main artist
print(i)

Song not found Song ID                                                                  31
Title                                                          Come With Me
Cleaned Title                                                  Come With Me
Artist                                      Puff Daddy Featuring Jimmy Page
Main Artist                                                      Puff Daddy
Feat                                                             Jimmy Page
Song Writers/Credits        J.P.Page, R.Plant, J.Bonham, S.J.Combs, M.Curry
Producer                                                              Diddy
Label                                                                  Epic
Album                                                                      
Duration                                                                   
Spotify Featured Artists                                                   
Spotify Found                                                            

In [ ]:
not_found = clean_single_songs_df[clean_single_songs_df["Spotify Found"] == 0].shape[0]
print("Even after preprocessing, we still have ", not_found, " songs not found")

Even after preprocessing, we still have  167  songs not found


Great! We now have only 167 missisng songs instead of 331! So our preprocessing was useful.

In [ ]:
clean_single_songs_df

Song ID                         Title                 Cleaned Title  \
0           0  I Don't Want To Miss A Thing  I Don't Want To Miss A Thing   
1           1               The First Night               The First Night   
2           2                         Crush                         Crush   
3           3                        My Way                        My Way   
4           4               The Boy Is Mine               The Boy Is Mine   
...       ...                           ...                           ...   
11446  135760               Passport Junkie               Passport Junkie   
11447  135773                     Talk Talk                     Talk Talk   
11448  135774                    Bad Dreams                    Bad Dreams   
11449  135794                   I Never Lie                   I Never Lie   
11450  135799                     Worst Way                     Worst Way   

                                 Artist     Main Artist         Feat  \
0                             Aerosmith       Aerosmith                
1                                Monica          Monica                
2                        Jennifer Paige  Jennifer Paige                
3                                 Usher           Usher                
4                       Brandy & Monica          Brandy       Monica   
...                                 ...             ...          ...   
11446                          Rod Wave        Rod Wave                
11447  Charli xcx Featuring Troye Sivan      Charli xcx  Troye Sivan   
11448                       Teddy Swims     Teddy Swims                
11449                          Zach Top        Zach Top                
11450                       Riley Green     Riley Green                

                                    Song Writers/Credits  \
0                                             D.E.Warren   
1        J.Dupri Mauldin, T.Savage, M.McLeod, P.J.Sawyer   
2             A.Goldmark, M.Mueller, B.Cosgrove, K.Clark   
3           J.Dupri Mauldin, M.L.Seal, Jr., U.Raymond IV   
4      R.Jerkins, B.R.Norwood, L.A.Daniels, F.Jerkins...   
...                                                  ...   
11446  R.M.Green, T.Kozluklu, K.B.Vyacheslavovich, D....   
11447  C.E.Aitchison, A.G.Cook, R.M.Birchard, T.S.Mel...   
11448  J.C.Dimsdale, J.H.Ryan, J.C.Bunetta, M.D.Zara,...   
11449                    Z.Top, C.Chamberlain, T.Nichols   
11450                                            R.Green   

                          Producer              Label  \
0                       M.Serletic           Columbia   
1                          J.Dupri             Arista   
2           A.Goldmark, J.Bralower     edel/Hollywood   
3                          J.Dupri      LaFace/Arista   
4      R.Jerkins, D.Austin, Brandy           Atlantic   
...                            ...                ...   
11446       T5, Exuising, Wonderyo              Alamo   
11447     Hudson Mohawke, A.G.Cook           Atlantic   
11448  J.H.Ryan, J.Bunetta, M.Zara  SWIMS Int./Warner   
11449                C.Chamberlain              Leo33   
11450                       D.Huff   Nashville Harbor   

                                                   Album Duration  \
0                        I Don't Want To Miss A Thing EP  299.723   
1                                        The Boy Is Mine  235.573   
2                                         Jennifer Paige  200.293   
3                                                 My Way  214.853   
4                                the boy is mine (Remix)  213.384   
...                                                  ...      ...   
11446                                           Last Lap  147.749   
11447  Brat and it’s completely different but also st...  173.076   
11448                                         Bad Dreams  184.577   
11449                          Cold Beer & Country Music  224.906   
11450                                       Way Out

We cut down the number of songs from 331 to 167, but we still have some missing songs. However, this will not hinder our work. Let's save this cleaned songs file, then proceed to some more data scrapping.

In [ ]:
clean_single_songs_df.to_csv('clean_single_songs.csv', index=False) #fix the name of columns and save it again

OK, looks good. Now let us scrape the data for the lyrics of the song.

**Only piece of code to run for next time**

Jusqu'ici on a une table qui contient toutes les chansons uniques de billbaord hot 100, sans duplicates.
* **Song ID**: un ID unqiue qu'on a attribue a une chanson. On l'utilisera comme cle primaire pour faire le sjointures sur d'autres tableaux.
* **Title**: Le titre original de la chanson, comme ecrit dans Billboard.
* **Cleaned Title**: La column de titre, mais on a applique une fonction de data cleaning qui decode les insultes, entre autres.
* **Artist**: Le nom du ou des artistes contirbants a la chanson, comme donne par billboard.
* **Main Artist**: L'artiste primaire de la chanson.
* **Feat**: Une version non clean des feats de la chanson, cette column est le resultat du split sur la colomne Main Artist.
* **Song Writers/ Credits**: Les auteurs de la chanson.
* **Producer**: Producteur(s) de la chanson.
* **Label**: Label / maison de disque (?)
* **Album**: Album auquel la chanson appartient. On a recupere ca de Spotify si disponible.
* **Duration**: Duree de la chanson en secondes.
* **Spotify Featured Artists**: Les artistes secondaires de la chanson, version clean comme donnee par Spotify si disponible.
* **Spotify Found**: 1 si a chanson a ete trouvee sur spotify, 0 sinon. Cette column nous aide pour remplir les donees manquantes, elle sera dropped plus tard.

In [ ]:
header, clean_single_songs=read_file("clean_single_songs.csv")
clean_single_songs_df= pd.DataFrame(clean_single_songs, columns=header)
clean_single_songs_df #11451 x 13

Song ID                         Title                 Cleaned Title  \
0           0  I Don't Want To Miss A Thing  I Don't Want To Miss A Thing   
1           1               The First Night               The First Night   
2           2                         Crush                         Crush   
3           3                        My Way                        My Way   
4           4               The Boy Is Mine               The Boy Is Mine   
...       ...                           ...                           ...   
11446  135760               Passport Junkie               Passport Junkie   
11447  135773                     Talk Talk                     Talk Talk   
11448  135774                    Bad Dreams                    Bad Dreams   
11449  135794                   I Never Lie                   I Never Lie   
11450  135799                     Worst Way                     Worst Way   

                                 Artist     Main Artist         Feat  \
0                             Aerosmith       Aerosmith                
1                                Monica          Monica                
2                        Jennifer Paige  Jennifer Paige                
3                                 Usher           Usher                
4                       Brandy & Monica          Brandy       Monica   
...                                 ...             ...          ...   
11446                          Rod Wave        Rod Wave                
11447  Charli xcx Featuring Troye Sivan      Charli xcx  Troye Sivan   
11448                       Teddy Swims     Teddy Swims                
11449                          Zach Top        Zach Top                
11450                       Riley Green     Riley Green                

                                    Song Writers/Credits  \
0                                             D.E.Warren   
1        J.Dupri Mauldin, T.Savage, M.McLeod, P.J.Sawyer   
2             A.Goldmark, M.Mueller, B.Cosgrove, K.Clark   
3           J.Dupri Mauldin, M.L.Seal, Jr., U.Raymond IV   
4      R.Jerkins, B.R.Norwood, L.A.Daniels, F.Jerkins...   
...                                                  ...   
11446  R.M.Green, T.Kozluklu, K.B.Vyacheslavovich, D....   
11447  C.E.Aitchison, A.G.Cook, R.M.Birchard, T.S.Mel...   
11448  J.C.Dimsdale, J.H.Ryan, J.C.Bunetta, M.D.Zara,...   
11449                    Z.Top, C.Chamberlain, T.Nichols   
11450                                            R.Green   

                          Producer              Label  \
0                       M.Serletic           Columbia   
1                          J.Dupri             Arista   
2           A.Goldmark, J.Bralower     edel/Hollywood   
3                          J.Dupri      LaFace/Arista   
4      R.Jerkins, D.Austin, Brandy           Atlantic   
...                            ...                ...   
11446       T5, Exuising, Wonderyo              Alamo   
11447     Hudson Mohawke, A.G.Cook           Atlantic   
11448  J.H.Ryan, J.Bunetta, M.Zara  SWIMS Int./Warner   
11449                C.Chamberlain              Leo33   
11450                       D.Huff   Nashville Harbor   

                                                   Album Duration  \
0                        I Don't Want To Miss A Thing EP  299.723   
1                                        The Boy Is Mine  235.573   
2                                         Jennifer Paige  200.293   
3                                                 My Way  214.853   
4                                the boy is mine (Remix)  213.384   
...                                                  ...      ...   
11446                                           Last Lap  147.749   
11447  Brat and it’s completely different but also st...  173.076   
11448                                         Bad Dreams  184.577   
11449                          Cold Beer & Country Music  224.906   
11450                                       Way Out

# Scrapping Missing DATA from GENIUS API

We will scrap data from the Genius Api to fill in the gaps of misisng features and  missing values. We will also get the release date of the song, since the available Spotify release date is garbage (sometimes it returned the release date of the song, sometimes of the album).


In [23]:
import bs4
import lxml
import pandas as pd
import urllib
from bs4 import BeautifulSoup
from urllib import request

In [24]:
import requests
from bs4 import BeautifulSoup
import time

In [27]:
import requests
GENIUS_ACCESS_TOKEN = "IvJZGAB3Xav52FL344TG-kajiMHdkVLkDF_e-00qTzJzq0Ts8L-O2aYdUOiyHdBS"
headers = {
    "Authorization": f"Bearer {GENIUS_ACCESS_TOKEN}",
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }


We're also going to try and complete the misisng data from spotify real quick.
So we know we have 167 misisng songs , but let's see how many Albums we are missing and how many durations we are missing.

In [ ]:
no_album= clean_single_songs_df[(clean_single_songs_df["Album"]=="") & (clean_single_songs_df["Spotify Found"]=="1") ].shape[0]
print("Out fo the songs found on spotify, we still have ", no_album, " song with NO album data not found")
no_duration= clean_single_songs_df[(clean_single_songs_df["Duration"]=="") & (clean_single_songs_df["Spotify Found"]=="1") ].shape[0]
print("Out fo the songs found on spotify, we still have ", no_duration, " song with NO duration data not found")

Out fo the songs found on spotify, we still have  0  song with NO album data not found
Out fo the songs found on spotify, we still have  0  song with NO duration data not found


Ok, turns out we got data on both features for all songs thta we found, so we are just missing these features for the songs we couldnt find on Spotify.

This isn't a hard fix, it means that if we have a better luck at finding songs usign genius API , we could just extract those features from the genius API to complete the data.

In [ ]:
import time
i=0
genius_found=[]
release_date=[]
album_genius=[]
for idx, row in clean_single_songs_df.iterrows():
  i+=1
  print(i)
  song_name = row["Cleaned Title"]
  artist_name=row["Main Artist"]
  url, id= search_song_GENIUS(song_name, artist_name)
  # if idx%2==0: time.sleep(0.2) #to avoid too many request per second
  Flag=1
  # Extract relevant details
  if(id==None):
    print("Song not found", row )

    print("-"*10)
    Flag=0
  else:  #song was found
    date= get_song_date(id)
    #extract album name of the data if it wasnt found on spotify
    if row["Spotify Found"]=='0' and row['Album']=="":
      print("Genius Found, but spotify didn't. Search for Album of:", song_name," by ", artist_name)
      album= get_song_album(id)
    else: album=None

  genius_found.append(Flag) #0 if not found else 1
  release_date.append(date if Flag else None)
  album_genius.append(album if Flag else None )

In [ ]:
print(len(genius_found))
print(len(release_date))
print(len(album_genius))

11451
11451
11451


Notice again what are the missing songs from the geniusAPI ?


In [ ]:
clean_single_songs_df["Release Date"]=release_date
clean_single_songs_df["Genius Album"]=album_genius
clean_single_songs_df["Genius Found"]=genius_found

In [ ]:
clean_single_songs_df.to_csv('clean_single_songs_genius.csv', index=False)

**Code to run next time**

In [ ]:
header, clean_single_songs=read_file("clean_single_songs_genius.csv")
clean_single_songs_df= pd.DataFrame(clean_single_songs, columns=header)
clean_single_songs_df #11451 x 16

Song ID                         Title                 Cleaned Title  \
0           0  I Don't Want To Miss A Thing  I Don't Want To Miss A Thing   
1           1               The First Night               The First Night   
2           2                         Crush                         Crush   
3           3                        My Way                        My Way   
4           4               The Boy Is Mine               The Boy Is Mine   
...       ...                           ...                           ...   
11446  135760               Passport Junkie               Passport Junkie   
11447  135773                     Talk Talk                     Talk Talk   
11448  135774                    Bad Dreams                    Bad Dreams   
11449  135794                   I Never Lie                   I Never Lie   
11450  135799                     Worst Way                     Worst Way   

                                 Artist     Main Artist         Feat  \
0                             Aerosmith       Aerosmith                
1                                Monica          Monica                
2                        Jennifer Paige  Jennifer Paige                
3                                 Usher           Usher                
4                       Brandy & Monica          Brandy       Monica   
...                                 ...             ...          ...   
11446                          Rod Wave        Rod Wave                
11447  Charli xcx Featuring Troye Sivan      Charli xcx  Troye Sivan   
11448                       Teddy Swims     Teddy Swims                
11449                          Zach Top        Zach Top                
11450                       Riley Green     Riley Green                

                                    Song Writers/Credits  \
0                                             D.E.Warren   
1        J.Dupri Mauldin, T.Savage, M.McLeod, P.J.Sawyer   
2             A.Goldmark, M.Mueller, B.Cosgrove, K.Clark   
3           J.Dupri Mauldin, M.L.Seal, Jr., U.Raymond IV   
4      R.Jerkins, B.R.Norwood, L.A.Daniels, F.Jerkins...   
...                                                  ...   
11446  R.M.Green, T.Kozluklu, K.B.Vyacheslavovich, D....   
11447  C.E.Aitchison, A.G.Cook, R.M.Birchard, T.S.Mel...   
11448  J.C.Dimsdale, J.H.Ryan, J.C.Bunetta, M.D.Zara,...   
11449                    Z.Top, C.Chamberlain, T.Nichols   
11450                                            R.Green   

                          Producer              Label  \
0                       M.Serletic           Columbia   
1                          J.Dupri             Arista   
2           A.Goldmark, J.Bralower     edel/Hollywood   
3                          J.Dupri      LaFace/Arista   
4      R.Jerkins, D.Austin, Brandy           Atlantic   
...                            ...                ...   
11446       T5, Exuising, Wonderyo              Alamo   
11447     Hudson Mohawke, A.G.Cook           Atlantic   
11448  J.H.Ryan, J.Bunetta, M.Zara  SWIMS Int./Warner   
11449                C.Chamberlain              Leo33   
11450                       D.Huff   Nashville Harbor   

                                                   Album Duration  \
0                        I Don't Want To Miss A Thing EP  299.723   
1                                        The Boy Is Mine  235.573   
2                                         Jennifer Paige  200.293   
3                                                 My Way  214.853   
4                                the boy is mine (Remix)  213.384   
...                                                  ...      ...   
11446                                           Last Lap  147.749   
11447  Brat and it’s completely different but also st...  173.076   
11448                                         Bad Dreams  184.577   
11449                          Cold Beer & Country Music  224.906   
11450                                       Way Out

In [ ]:
#
df= clean_single_songs_df[clean_single_songs_df["Genius Found"]=='0']
print("We weren't able to find : ",len(df), " songs using Genius API")


We weren't able to find :  6  songs using Genius API


Akright, looks like only 6 songs couldnt be found on geniusAPI. What interests us thought is the numbe rof songs for which we dont have releas dates. So let's see that.

In [ ]:
df = clean_single_songs_df[clean_single_songs_df["Release Date"]==""]
print("We are missing the release dates of : ",len(df), " songs using Genius API")


We are missing the release dates of :  621  songs using Genius API


Let's see if we filled the gaps of the album release


In [ ]:
df = clean_single_songs_df[(clean_single_songs_df["Genius Album"]!="") & (clean_single_songs_df["Album"]=="")]
print("We filled the album gap of : ",len(df), " songs using Genius API")

We filled the album gap of :  129  songs using Genius API


In [ ]:
df

Song ID                      Title              Cleaned Title  \
31         31               Come With Me               Come With Me   
65         65  If You Could Read My Mind  If You Could Read My Mind   
67         67                  Delicious                  Delicious   
80         80                 Here We Go                 Here We Go   
85         85          '98 Thug Paradise          '98 Thug Paradise   
...       ...                        ...                        ...   
9951   123309              I'm Dat N***a              i'm dat nigga   
10092  124175           Call Me Everyday           Call Me Everyday   
10997  132230                 Pop Ur Sht                 Pop Ur Sht   
11152  133405             7 Minute Drill             7 Minute Drill   
11390  135262             Blue Green Red             Blue Green Red   

                                                  Artist  \
31                       Puff Daddy Featuring Jimmy Page   
65      Stars On 54: Ultra Nate, Amber, Jocelyn Enriquez   
67                                            Pure Sugar   
80     Funkmaster Flex Presents Khadejia Featuring Pr...   
85                             Tragedy, Capone, Infinite   
...                                                  ...   
9951                                              Future   
10092                       Chris Brown Featuring WizKid   
10997               21 Savage, Young Thug & Metro Boomin   
11152                                            J. Cole   
11390                                              Drake   

                   Main Artist                        Feat  \
31                  Puff Daddy                  Jimmy Page   
65     Stars On 54: Ultra Nate     Amber, Jocelyn Enriquez   
67                  Pure Sugar                               
80             Funkmaster Flex  Khadejia Featuring Product   
85                     Tragedy            Capone, Infinite   
...                        ...                         ...   
9951                    Future                               
10092              Chris Brown                      WizKid   
10997                21 Savage   Young Thug & Metro Boomin   
11152                  J. Cole                               
11390                    Drake                               

                                    Song Writers/Credits  \
31       J.P.Page, R.Plant, J.Bonham, S.J.Combs, M.Curry   
65                                           G.Lightfoot   
67     P.Lorimer, R.Vission, J.Johnson, Kibble, M.Bra...   
80                W.Jean, K.Bass, D.McRae, M.Moore-Hough   
85                                       A.Moody, W.Hale   
...                                                  ...   
9951        N.D.Cash, D.L.J.Avery, N.Santos, J.H.Luellen   
10092  C.M.Brown, M.Adeyinka, M.Akunwata, L.D.Youngbl...   
10997    S.B.A.Joseph, J.L.Williams, L.T.Wayne, A.Ritter   
11152                                             J.Cole   
11390                                           A.Graham   

                                   Producer                       Label Album  \
31                                    Diddy                        Epic         
65                      The Berman Brothers                   Tommy Boy         
67                     P.Lorimer, R.Vission                      Geffen         
80                  W.Jean, Funkmaster Flex                    Loud/RCA         
85                         A.McLean, D-Moet                    H.O.L.A.         
...                                     ...                         ...   ...   
9951   DY Krazy, Nicky Slowburnz, J.Luellen              Freebandz/Epic         
10092                Blaise Beatz, Roccstar                     CBE/RCA         
10997                Metro Boomin, A.Ritter         Slaughter Gang/Epic         
11152           T-Minus, Conductor Williams  Cole World/Interscope/ICLG         
11390                            Not Listed          OVO Sound/Republic    

That's  great, the only annoying part is our 600 missing release dates, we will see how to fix this using Wikipedia. For now, we save our data.


**WHAT TO RUN NEXT TIME**

In [ ]:
header, clean_single_songs=read_file("clean_single_songs_genius.csv")
clean_single_songs_df= pd.DataFrame(clean_single_songs, columns=header)
clean_single_songs_df #11451 x 16

Song ID                         Title                 Cleaned Title  \
0           0  I Don't Want To Miss A Thing  I Don't Want To Miss A Thing   
1           1               The First Night               The First Night   
2           2                         Crush                         Crush   
3           3                        My Way                        My Way   
4           4               The Boy Is Mine               The Boy Is Mine   
...       ...                           ...                           ...   
11446  135760               Passport Junkie               Passport Junkie   
11447  135773                     Talk Talk                     Talk Talk   
11448  135774                    Bad Dreams                    Bad Dreams   
11449  135794                   I Never Lie                   I Never Lie   
11450  135799                     Worst Way                     Worst Way   

                                 Artist     Main Artist         Feat  \
0                             Aerosmith       Aerosmith                
1                                Monica          Monica                
2                        Jennifer Paige  Jennifer Paige                
3                                 Usher           Usher                
4                       Brandy & Monica          Brandy       Monica   
...                                 ...             ...          ...   
11446                          Rod Wave        Rod Wave                
11447  Charli xcx Featuring Troye Sivan      Charli xcx  Troye Sivan   
11448                       Teddy Swims     Teddy Swims                
11449                          Zach Top        Zach Top                
11450                       Riley Green     Riley Green                

                                    Song Writers/Credits  \
0                                             D.E.Warren   
1        J.Dupri Mauldin, T.Savage, M.McLeod, P.J.Sawyer   
2             A.Goldmark, M.Mueller, B.Cosgrove, K.Clark   
3           J.Dupri Mauldin, M.L.Seal, Jr., U.Raymond IV   
4      R.Jerkins, B.R.Norwood, L.A.Daniels, F.Jerkins...   
...                                                  ...   
11446  R.M.Green, T.Kozluklu, K.B.Vyacheslavovich, D....   
11447  C.E.Aitchison, A.G.Cook, R.M.Birchard, T.S.Mel...   
11448  J.C.Dimsdale, J.H.Ryan, J.C.Bunetta, M.D.Zara,...   
11449                    Z.Top, C.Chamberlain, T.Nichols   
11450                                            R.Green   

                          Producer              Label  \
0                       M.Serletic           Columbia   
1                          J.Dupri             Arista   
2           A.Goldmark, J.Bralower     edel/Hollywood   
3                          J.Dupri      LaFace/Arista   
4      R.Jerkins, D.Austin, Brandy           Atlantic   
...                            ...                ...   
11446       T5, Exuising, Wonderyo              Alamo   
11447     Hudson Mohawke, A.G.Cook           Atlantic   
11448  J.H.Ryan, J.Bunetta, M.Zara  SWIMS Int./Warner   
11449                C.Chamberlain              Leo33   
11450                       D.Huff   Nashville Harbor   

                                                   Album Duration  \
0                        I Don't Want To Miss A Thing EP  299.723   
1                                        The Boy Is Mine  235.573   
2                                         Jennifer Paige  200.293   
3                                                 My Way  214.853   
4                                the boy is mine (Remix)  213.384   
...                                                  ...      ...   
11446                                           Last Lap  147.749   
11447  Brat and it’s completely different but also st...  173.076   
11448                                         Bad Dreams  184.577   
11449                          Cold Beer & Country Music  224.906   
11450                                       Way Out

# Scrapping the Lyrics

Now that we have some better cleaned artist name and song titles, and that we have set up GENIUS API, we will proceed to get the lyrics of the songs.

In [20]:
def get_lyrics(song, artist):
    # Construct the URL
    url = f"https://api.lyrics.ovh/v1/{artist}/{song}"

    # Send the request
    response = requests.get(url)

    # Check if the response is valid
    if response.status_code == 200:
        data = response.json()
        # Return the lyrics from the response
        return data.get('lyrics', None)
    else:
        return None

    return None




In [ ]:
lyrics= get_lyrics("I Don't Want To Miss A Thing","Aerosmith")
print(lyrics)

I could stay awake just to hear you breathing
Watch you smile while you are sleeping
While you're far away and dreaming
I could spend my life in this sweet surrender
I could stay lost in this moment forever
Every moment spent with you is a moment I treasure



Don't wanna close my eyes

I don't wanna fall asleep

'Coz I'd miss you baby

And I don't wanna miss a thing

'Coz even when I dream of you

The sweetest dream would never do

I'd still miss you baby

And I don't wanna miss a thing



Laying close to you

Feeling your heart beating

And I'm wondering what you're dreaming

Wondering if it's me you're seeing

Then I kiss your eyes

And thank God we're together

I just want to stay with you in this moment forever

Forever and ever



Don't wanna close my eyes

I don't wanna fall asleep

'Coz I'd miss you baby

And I don't wanna miss a thing

'Coz even when I dream of you

The sweetest dream would never do

I'd still miss you baby

And I don't wanna miss a thing



I don't wanna miss

In [ ]:
import time
i=0
lyrics_all=[]
for idx, row in clean_single_songs_df.iterrows():
  i+=1
  print(i)
  song_name = row["Cleaned Title"]
  artist_name=row["Main Artist"]
  # idx%2==0: time.sleep(0.2) #slow down
  lyrics=get_lyrics(song_name, artist_name)
  if lyrics==None: print("Couln't find lyric for: ", artist_name, song_name)
  lyrics_all.append(lyrics)


Streaming output truncated to the last 5000 lines.
7120
Couln't find lyric for:  JAY-Z Kill Jay Z
7121
7122
Couln't find lyric for:  JAY-Z Caught Their Eyes
7123
Couln't find lyric for:  JAY-Z Moonlight
7124
7125
7126
7127
7128
Couln't find lyric for:  21 Savage Famous
7129
7130
7131
Couln't find lyric for:  Khalid Young Dumb & Broke
7132
7133
7134
7135
7136
Couln't find lyric for:  Meek Mill Wins & Losses
7137
Couln't find lyric for:  Descendants 2 Cast It's Goin' Down
7138
7139
7140
7141
7142
7143
7144
Couln't find lyric for:  Thomas Rhett Unforgettable
7145
7146
7147
7148
7149
7150
7151
7152
Couln't find lyric for:  Kesha Learn To Let Go
7153
7154
7155
7156
7157
7158
Couln't find lyric for:  P!nk What About Us
7159
7160
Couln't find lyric for:  Jacquees B E D
7161
Couln't find lyric for:  Sofia Carson Chillin' Like A Villain
7162
7163
7164
7165
7166
7167
7168
7169
7170
7171
7172
7173
7174
Couln't find lyric for:  RiceGum Its Every Night Sis
7175
7176
7177
7178
Couln't find lyric for

Regardons combien de lyrics on n'a pas pu trouver

In [ ]:
clean_single_songs_df["Lyrics"]= lyrics_all

In [ ]:
clean_single_songs_df

Song ID                         Title                 Cleaned Title  \
0           0  I Don't Want To Miss A Thing  I Don't Want To Miss A Thing   
1           1               The First Night               The First Night   
2           2                         Crush                         Crush   
3           3                        My Way                        My Way   
4           4               The Boy Is Mine               The Boy Is Mine   
...       ...                           ...                           ...   
11446  135760               Passport Junkie               Passport Junkie   
11447  135773                     Talk Talk                     Talk Talk   
11448  135774                    Bad Dreams                    Bad Dreams   
11449  135794                   I Never Lie                   I Never Lie   
11450  135799                     Worst Way                     Worst Way   

                                 Artist     Main Artist         Feat  \
0                             Aerosmith       Aerosmith                
1                                Monica          Monica                
2                        Jennifer Paige  Jennifer Paige                
3                                 Usher           Usher                
4                       Brandy & Monica          Brandy       Monica   
...                                 ...             ...          ...   
11446                          Rod Wave        Rod Wave                
11447  Charli xcx Featuring Troye Sivan      Charli xcx  Troye Sivan   
11448                       Teddy Swims     Teddy Swims                
11449                          Zach Top        Zach Top                
11450                       Riley Green     Riley Green                

                                    Song Writers/Credits  \
0                                             D.E.Warren   
1        J.Dupri Mauldin, T.Savage, M.McLeod, P.J.Sawyer   
2             A.Goldmark, M.Mueller, B.Cosgrove, K.Clark   
3           J.Dupri Mauldin, M.L.Seal, Jr., U.Raymond IV   
4      R.Jerkins, B.R.Norwood, L.A.Daniels, F.Jerkins...   
...                                                  ...   
11446  R.M.Green, T.Kozluklu, K.B.Vyacheslavovich, D....   
11447  C.E.Aitchison, A.G.Cook, R.M.Birchard, T.S.Mel...   
11448  J.C.Dimsdale, J.H.Ryan, J.C.Bunetta, M.D.Zara,...   
11449                    Z.Top, C.Chamberlain, T.Nichols   
11450                                            R.Green   

                          Producer              Label  \
0                       M.Serletic           Columbia   
1                          J.Dupri             Arista   
2           A.Goldmark, J.Bralower     edel/Hollywood   
3                          J.Dupri      LaFace/Arista   
4      R.Jerkins, D.Austin, Brandy           Atlantic   
...                            ...                ...   
11446       T5, Exuising, Wonderyo              Alamo   
11447     Hudson Mohawke, A.G.Cook           Atlantic   
11448  J.H.Ryan, J.Bunetta, M.Zara  SWIMS Int./Warner   
11449                C.Chamberlain              Leo33   
11450                       D.Huff   Nashville Harbor   

                                                   Album Duration  \
0                        I Don't Want To Miss A Thing EP  299.723   
1                                        The Boy Is Mine  235.573   
2                                         Jennifer Paige  200.293   
3                                                 My Way  214.853   
4                                the boy is mine (Remix)  213.384   
...                                                  ...      ...   
11446                                           Last Lap  147.749   
11447  Brat and it’s completely different but also st...  173.076   
11448                                         Bad Dreams  184.577   
11449                          Cold Beer & Country Music  224.906   
11450                                       Way Out

Great, we got our songs, let's see how much we are missing.


In [ ]:
df= clean_single_songs_df[clean_single_songs_df["Lyrics"].isna()]
print(f"We are misisng lyrics for {len(df)} songs")

We are misisng lyrics for 1764 songs


We have 1764 songs that we coulnd't get lyrics for. Let's see if we can fix that.

We will ge tthe songs from another platform.

In [ ]:
clean_single_songs_df.to_csv('clean_single_songs_genius_lyrics.csv', index=False) #fix the name of columns and save it again

## whats to run next time

In [ ]:
import pandas as pd

songs_df = pd.read_csv("clean_single_songs_genius_lyrics.csv")

In [ ]:
songs_df

Song ID                         Title                 Cleaned Title  \
0            0  I Don't Want To Miss A Thing  I Don't Want To Miss A Thing   
1            1               The First Night               The First Night   
2            2                         Crush                         Crush   
3            3                        My Way                        My Way   
4            4               The Boy Is Mine               The Boy Is Mine   
...        ...                           ...                           ...   
11446   135760               Passport Junkie               Passport Junkie   
11447   135773                     Talk Talk                     Talk Talk   
11448   135774                    Bad Dreams                    Bad Dreams   
11449   135794                   I Never Lie                   I Never Lie   
11450   135799                     Worst Way                     Worst Way   

                                 Artist     Main Artist         Feat  \
0                             Aerosmith       Aerosmith          NaN   
1                                Monica          Monica          NaN   
2                        Jennifer Paige  Jennifer Paige          NaN   
3                                 Usher           Usher          NaN   
4                       Brandy & Monica          Brandy       Monica   
...                                 ...             ...          ...   
11446                          Rod Wave        Rod Wave          NaN   
11447  Charli xcx Featuring Troye Sivan      Charli xcx  Troye Sivan   
11448                       Teddy Swims     Teddy Swims          NaN   
11449                          Zach Top        Zach Top          NaN   
11450                       Riley Green     Riley Green          NaN   

                                    Song Writers/Credits  \
0                                             D.E.Warren   
1        J.Dupri Mauldin, T.Savage, M.McLeod, P.J.Sawyer   
2             A.Goldmark, M.Mueller, B.Cosgrove, K.Clark   
3           J.Dupri Mauldin, M.L.Seal, Jr., U.Raymond IV   
4      R.Jerkins, B.R.Norwood, L.A.Daniels, F.Jerkins...   
...                                                  ...   
11446  R.M.Green, T.Kozluklu, K.B.Vyacheslavovich, D....   
11447  C.E.Aitchison, A.G.Cook, R.M.Birchard, T.S.Mel...   
11448  J.C.Dimsdale, J.H.Ryan, J.C.Bunetta, M.D.Zara,...   
11449                    Z.Top, C.Chamberlain, T.Nichols   
11450                                            R.Green   

                          Producer              Label  \
0                       M.Serletic           Columbia   
1                          J.Dupri             Arista   
2           A.Goldmark, J.Bralower     edel/Hollywood   
3                          J.Dupri      LaFace/Arista   
4      R.Jerkins, D.Austin, Brandy           Atlantic   
...                            ...                ...   
11446       T5, Exuising, Wonderyo              Alamo   
11447     Hudson Mohawke, A.G.Cook           Atlantic   
11448  J.H.Ryan, J.Bunetta, M.Zara  SWIMS Int./Warner   
11449                C.Chamberlain              Leo33   
11450                       D.Huff   Nashville Harbor   

                                                   Album  Duration  \
0                        I Don't Want To Miss A Thing EP   299.723   
1                                        The Boy Is Mine   235.573   
2                                         Jennifer Paige   200.293   
3                                                 My Way   214.853   
4                                the boy is mine (Remix)   213.384   
...                                                  ...       ...   
11446                                           Last Lap   147.749   
11447  Brat and it’s completely different but also st...   173.076   
11448                                         Bad Dreams   184.577   
11449                          Cold Beer & Country Music   224.906   
11450                        

In [ ]:
songs_df = songs_df.where(pd.notna(songs_df), None)
songs_df

Song ID                         Title                 Cleaned Title  \
0            0  I Don't Want To Miss A Thing  I Don't Want To Miss A Thing   
1            1               The First Night               The First Night   
2            2                         Crush                         Crush   
3            3                        My Way                        My Way   
4            4               The Boy Is Mine               The Boy Is Mine   
...        ...                           ...                           ...   
11446   135760               Passport Junkie               Passport Junkie   
11447   135773                     Talk Talk                     Talk Talk   
11448   135774                    Bad Dreams                    Bad Dreams   
11449   135794                   I Never Lie                   I Never Lie   
11450   135799                     Worst Way                     Worst Way   

                                 Artist     Main Artist         Feat  \
0                             Aerosmith       Aerosmith         None   
1                                Monica          Monica         None   
2                        Jennifer Paige  Jennifer Paige         None   
3                                 Usher           Usher         None   
4                       Brandy & Monica          Brandy       Monica   
...                                 ...             ...          ...   
11446                          Rod Wave        Rod Wave         None   
11447  Charli xcx Featuring Troye Sivan      Charli xcx  Troye Sivan   
11448                       Teddy Swims     Teddy Swims         None   
11449                          Zach Top        Zach Top         None   
11450                       Riley Green     Riley Green         None   

                                    Song Writers/Credits  \
0                                             D.E.Warren   
1        J.Dupri Mauldin, T.Savage, M.McLeod, P.J.Sawyer   
2             A.Goldmark, M.Mueller, B.Cosgrove, K.Clark   
3           J.Dupri Mauldin, M.L.Seal, Jr., U.Raymond IV   
4      R.Jerkins, B.R.Norwood, L.A.Daniels, F.Jerkins...   
...                                                  ...   
11446  R.M.Green, T.Kozluklu, K.B.Vyacheslavovich, D....   
11447  C.E.Aitchison, A.G.Cook, R.M.Birchard, T.S.Mel...   
11448  J.C.Dimsdale, J.H.Ryan, J.C.Bunetta, M.D.Zara,...   
11449                    Z.Top, C.Chamberlain, T.Nichols   
11450                                            R.Green   

                          Producer              Label  \
0                       M.Serletic           Columbia   
1                          J.Dupri             Arista   
2           A.Goldmark, J.Bralower     edel/Hollywood   
3                          J.Dupri      LaFace/Arista   
4      R.Jerkins, D.Austin, Brandy           Atlantic   
...                            ...                ...   
11446       T5, Exuising, Wonderyo              Alamo   
11447     Hudson Mohawke, A.G.Cook           Atlantic   
11448  J.H.Ryan, J.Bunetta, M.Zara  SWIMS Int./Warner   
11449                C.Chamberlain              Leo33   
11450                       D.Huff   Nashville Harbor   

                                                   Album  Duration  \
0                        I Don't Want To Miss A Thing EP   299.723   
1                                        The Boy Is Mine   235.573   
2                                         Jennifer Paige   200.293   
3                                                 My Way   214.853   
4                                the boy is mine (Remix)   213.384   
...                                                  ...       ...   
11446                                           Last Lap   147.749   
11447  Brat and it’s completely different but also st...   173.076   
11448                                         Bad Dreams   184.577   
11449                          Cold Beer & Country Music   224.906   
11450                        

In [ ]:
songs_df["Song ID"] = songs_df["Song ID"].astype(str).apply(lambda x: "S" + x)
songs_df

Song ID                         Title                 Cleaned Title  \
0           S0  I Don't Want To Miss A Thing  I Don't Want To Miss A Thing   
1           S1               The First Night               The First Night   
2           S2                         Crush                         Crush   
3           S3                        My Way                        My Way   
4           S4               The Boy Is Mine               The Boy Is Mine   
...        ...                           ...                           ...   
11446  S135760               Passport Junkie               Passport Junkie   
11447  S135773                     Talk Talk                     Talk Talk   
11448  S135774                    Bad Dreams                    Bad Dreams   
11449  S135794                   I Never Lie                   I Never Lie   
11450  S135799                     Worst Way                     Worst Way   

                                 Artist     Main Artist         Feat  \
0                             Aerosmith       Aerosmith         None   
1                                Monica          Monica         None   
2                        Jennifer Paige  Jennifer Paige         None   
3                                 Usher           Usher         None   
4                       Brandy & Monica          Brandy       Monica   
...                                 ...             ...          ...   
11446                          Rod Wave        Rod Wave         None   
11447  Charli xcx Featuring Troye Sivan      Charli xcx  Troye Sivan   
11448                       Teddy Swims     Teddy Swims         None   
11449                          Zach Top        Zach Top         None   
11450                       Riley Green     Riley Green         None   

                                    Song Writers/Credits  \
0                                             D.E.Warren   
1        J.Dupri Mauldin, T.Savage, M.McLeod, P.J.Sawyer   
2             A.Goldmark, M.Mueller, B.Cosgrove, K.Clark   
3           J.Dupri Mauldin, M.L.Seal, Jr., U.Raymond IV   
4      R.Jerkins, B.R.Norwood, L.A.Daniels, F.Jerkins...   
...                                                  ...   
11446  R.M.Green, T.Kozluklu, K.B.Vyacheslavovich, D....   
11447  C.E.Aitchison, A.G.Cook, R.M.Birchard, T.S.Mel...   
11448  J.C.Dimsdale, J.H.Ryan, J.C.Bunetta, M.D.Zara,...   
11449                    Z.Top, C.Chamberlain, T.Nichols   
11450                                            R.Green   

                          Producer              Label  \
0                       M.Serletic           Columbia   
1                          J.Dupri             Arista   
2           A.Goldmark, J.Bralower     edel/Hollywood   
3                          J.Dupri      LaFace/Arista   
4      R.Jerkins, D.Austin, Brandy           Atlantic   
...                            ...                ...   
11446       T5, Exuising, Wonderyo              Alamo   
11447     Hudson Mohawke, A.G.Cook           Atlantic   
11448  J.H.Ryan, J.Bunetta, M.Zara  SWIMS Int./Warner   
11449                C.Chamberlain              Leo33   
11450                       D.Huff   Nashville Harbor   

                                                   Album  Duration  \
0                        I Don't Want To Miss A Thing EP   299.723   
1                                        The Boy Is Mine   235.573   
2                                         Jennifer Paige   200.293   
3                                                 My Way   214.853   
4                                the boy is mine (Remix)   213.384   
...                                                  ...       ...   
11446                                           Last Lap   147.749   
11447  Brat and it’s completely different but also st...   173.076   
11448                                         Bad Dreams   184.577   
11449                          Cold Beer & Country Music   224.906   
11450                        

In [ ]:
songs_df.apply(pd.Series.unique)

Song ID                     [S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, ...
Title                       [I Don't Want To Miss A Thing, The First Night...
Cleaned Title               [I Don't Want To Miss A Thing, The First Night...
Artist                      [Aerosmith, Monica, Jennifer Paige, Usher, Bra...
Main Artist                 [Aerosmith, Monica, Jennifer Paige, Usher, Bra...
Feat                        [None, Monica, Puff Daddy, Missy "Misdemeanor"...
Song Writers/Credits        [D.E.Warren, J.Dupri Mauldin, T.Savage, M.McLe...
Producer                    [M.Serletic, J.Dupri, A.Goldmark, J.Bralower, ...
Label                       [Columbia, Arista, edel/Hollywood, LaFace/Aris...
Album                       [I Don't Want To Miss A Thing EP, The Boy Is M...
Duration                    [299.723, 235.573, 200.293, 214.853, 213.384, ...
Spotify Featured Artists    [None, Brandy,Monica, Lord Tariq,Peter Gunz, C...
Spotify Found                                                          [1, 0]
Release Date                [1998-08-18, 1998-07-07, 1998-06-16, 1997-09-1...
Genius Album                [None, Godzilla: The Album, 54 (Music From the...
Genius Found                                                           [1, 0]
Lyrics                      [I could stay awake just to hear you breathing...
dtype: object

In [ ]:
temp= pd.read_csv("clean_single_songs_DWI_merge_OTHER_FEATURES.csv")
temp


Song ID                         Title                 Cleaned Title  \
0            0  I Don't Want To Miss A Thing  I Don't Want To Miss A Thing   
1            1               The First Night               The First Night   
2            2                         Crush                         Crush   
3            3                        My Way                        My Way   
4            4               The Boy Is Mine               The Boy Is Mine   
...        ...                           ...                           ...   
11446   135760               Passport Junkie               Passport Junkie   
11447   135773                     Talk Talk                     Talk Talk   
11448   135774                    Bad Dreams                    Bad Dreams   
11449   135794                   I Never Lie                   I Never Lie   
11450   135799                     Worst Way                     Worst Way   

                                 Artist     Main Artist         Feat  \
0                             Aerosmith       Aerosmith          NaN   
1                                Monica          Monica          NaN   
2                        Jennifer Paige  Jennifer Paige          NaN   
3                                 Usher           Usher          NaN   
4                       Brandy & Monica          Brandy       Monica   
...                                 ...             ...          ...   
11446                          Rod Wave        Rod Wave          NaN   
11447  Charli xcx Featuring Troye Sivan      Charli xcx  Troye Sivan   
11448                       Teddy Swims     Teddy Swims          NaN   
11449                          Zach Top        Zach Top          NaN   
11450                       Riley Green     Riley Green          NaN   

                                    Song Writers/Credits  \
0                                             D.E.Warren   
1        J.Dupri Mauldin, T.Savage, M.McLeod, P.J.Sawyer   
2             A.Goldmark, M.Mueller, B.Cosgrove, K.Clark   
3           J.Dupri Mauldin, M.L.Seal, Jr., U.Raymond IV   
4      R.Jerkins, B.R.Norwood, L.A.Daniels, F.Jerkins...   
...                                                  ...   
11446  R.M.Green, T.Kozluklu, K.B.Vyacheslavovich, D....   
11447  C.E.Aitchison, A.G.Cook, R.M.Birchard, T.S.Mel...   
11448  J.C.Dimsdale, J.H.Ryan, J.C.Bunetta, M.D.Zara,...   
11449                    Z.Top, C.Chamberlain, T.Nichols   
11450                                            R.Green   

                          Producer              Label  \
0                       M.Serletic           Columbia   
1                          J.Dupri             Arista   
2           A.Goldmark, J.Bralower     edel/Hollywood   
3                          J.Dupri      LaFace/Arista   
4      R.Jerkins, D.Austin, Brandy           Atlantic   
...                            ...                ...   
11446       T5, Exuising, Wonderyo              Alamo   
11447     Hudson Mohawke, A.G.Cook           Atlantic   
11448  J.H.Ryan, J.Bunetta, M.Zara  SWIMS Int./Warner   
11449                C.Chamberlain              Leo33   
11450                       D.Huff   Nashville Harbor   

                                                   Album  Duration  \
0                        I Don't Want To Miss A Thing EP   299.723   
1                                        The Boy Is Mine   235.573   
2                                         Jennifer Paige   200.293   
3                                                 My Way   214.853   
4                                the boy is mine (Remix)   213.384   
...                                                  ...       ...   
11446                                           Last Lap   147.749   
11447  Brat and it’s completely different but also st...   173.076   
11448                                         Bad Dreams   184.577   
11449                          Cold Beer & Country Music   224.906   
11450                        

In [ ]:
songs_df["Genre"]= temp["Genre"]
songs_df["Tempo"]= temp["Tempo"]
songs_df["Loudness"]= temp["Loudness"]


In [ ]:
songs_df = songs_df.where(pd.notna(songs_df), None)
songs_df

Song ID                         Title                 Cleaned Title  \
0           S0  I Don't Want To Miss A Thing  I Don't Want To Miss A Thing   
1           S1               The First Night               The First Night   
2           S2                         Crush                         Crush   
3           S3                        My Way                        My Way   
4           S4               The Boy Is Mine               The Boy Is Mine   
...        ...                           ...                           ...   
11446  S135760               Passport Junkie               Passport Junkie   
11447  S135773                     Talk Talk                     Talk Talk   
11448  S135774                    Bad Dreams                    Bad Dreams   
11449  S135794                   I Never Lie                   I Never Lie   
11450  S135799                     Worst Way                     Worst Way   

                                 Artist     Main Artist         Feat  \
0                             Aerosmith       Aerosmith         None   
1                                Monica          Monica         None   
2                        Jennifer Paige  Jennifer Paige         None   
3                                 Usher           Usher         None   
4                       Brandy & Monica          Brandy       Monica   
...                                 ...             ...          ...   
11446                          Rod Wave        Rod Wave         None   
11447  Charli xcx Featuring Troye Sivan      Charli xcx  Troye Sivan   
11448                       Teddy Swims     Teddy Swims         None   
11449                          Zach Top        Zach Top         None   
11450                       Riley Green     Riley Green         None   

                                    Song Writers/Credits  \
0                                             D.E.Warren   
1        J.Dupri Mauldin, T.Savage, M.McLeod, P.J.Sawyer   
2             A.Goldmark, M.Mueller, B.Cosgrove, K.Clark   
3           J.Dupri Mauldin, M.L.Seal, Jr., U.Raymond IV   
4      R.Jerkins, B.R.Norwood, L.A.Daniels, F.Jerkins...   
...                                                  ...   
11446  R.M.Green, T.Kozluklu, K.B.Vyacheslavovich, D....   
11447  C.E.Aitchison, A.G.Cook, R.M.Birchard, T.S.Mel...   
11448  J.C.Dimsdale, J.H.Ryan, J.C.Bunetta, M.D.Zara,...   
11449                    Z.Top, C.Chamberlain, T.Nichols   
11450                                            R.Green   

                          Producer              Label  \
0                       M.Serletic           Columbia   
1                          J.Dupri             Arista   
2           A.Goldmark, J.Bralower     edel/Hollywood   
3                          J.Dupri      LaFace/Arista   
4      R.Jerkins, D.Austin, Brandy           Atlantic   
...                            ...                ...   
11446       T5, Exuising, Wonderyo              Alamo   
11447     Hudson Mohawke, A.G.Cook           Atlantic   
11448  J.H.Ryan, J.Bunetta, M.Zara  SWIMS Int./Warner   
11449                C.Chamberlain              Leo33   
11450                       D.Huff   Nashville Harbor   

                                                   Album  Duration  \
0                        I Don't Want To Miss A Thing EP   299.723   
1                                        The Boy Is Mine   235.573   
2                                         Jennifer Paige   200.293   
3                                                 My Way   214.853   
4                                the boy is mine (Remix)   213.384   
...                                                  ...       ...   
11446                                           Last Lap   147.749   
11447  Brat and it’s completely different but also st...   173.076   
11448                                         Bad Dreams   184.577   
11449                          Cold Beer & Country Music   224.906   
11450                        

In [ ]:
print("None values Lyrics", songs_df["Lyrics"].isna().sum())
print("None values Duration", songs_df["Duration"].isna().sum())
print("None values date", songs_df["Release Date"].isna().sum())
print("None values loudness", songs_df["Loudness"].isna().sum())
print("None values tempo", songs_df["Tempo"].isna().sum())
print("None values genre", songs_df["Genre"].isna().sum())

None values Lyrics 1764
None values Duration 167
None values date 621
None values loudness 1117
None values tempo 1117
None values genre 103


In [ ]:
songs_df.to_csv('songs_data_final.csv', index=False)

# Extra grammys songs

### sptofy search

So from grammys we found some extra songs that werent on billbaord. we will add them to our songs_data.

In [6]:
import pandas as pd

In [17]:
extra_songs_df= pd.read_csv("missing_songs_grammy_dwi.csv")
extra_songs_df

Song ID                      Title              Cleaned Title  \
0       NaN                  Asteroids                  Asteroids   
1       NaN          Not Strong Enough          Not Strong Enough   
2       NaN                    Worship                    Worship   
3       NaN                  Butterfly                  Butterfly   
4       NaN                        A&W                        A&W   
5       NaN     SCIENTISTS & ENGINEERS     Scientists & Engineers   
6       NaN     You And Me On The Rock     You And Me On The Rock   
7       NaN         Don't Shut Me Down         Don'T Shut Me Down   
8       NaN             Just Like That             Just Like That   
9       NaN              Right On Time              Right On Time   
10      NaN    I Get A Kick Out Of You    I Get A Kick Out Of You   
11      NaN                    Freedom                    Freedom   
12      NaN  I Still Have Faith In You  I Still Have Faith In You   
13      NaN              Right On Time              Right On Time   
14      NaN              Fight For You              Fight For You   
15      NaN          A Beautiful Noise          A Beautiful Noise   
16      NaN                 Bath Salts                 Bath Salts   
17      NaN                     Colors                     Colors   
18      NaN            I Can't Breathe            I Can'T Breathe   
19      NaN                 Hard Place                 Hard Place   
20      NaN                    Hey, Ma                     Hey Ma   
21      NaN    Norman F***ing Rockwell    Norman Fucking Rockwell   
22      NaN                 Hard Place                 Hard Place   
23      NaN       Bring My Flowers Now       Bring My Flowers Now   
24      NaN                   Bad Idea                   Bad Idea   
25      NaN                   The Joke                   The Joke   
26      NaN                   The Joke                   The Joke   
27      NaN                        Win                        Win   
28      NaN                King's Dead                King'S Dead   
29      NaN                      Sassy                      Sassy   
30      NaN                   Chase Me                   Chase Me   
31      NaN                Really Love                Really Love   
32      NaN           F***in' Problems           Fuckin' Problems   
33      NaN                  Daughters                  Daughters   
34      NaN                   Holocene                   Holocene   
35      NaN                   Holocene                   Holocene   
36      NaN        Beg Steal Or Borrow        Beg Steal Or Borrow   
37      NaN     Please Read The Letter     Please Read The Letter   
38      NaN            Sexual Eruption            Sexual Eruption   
39      NaN           Here We Go Again           Here We Go Again   
40      NaN      Keep Me In Your Heart      Keep Me In Your Heart   
41      NaN                    Walk On                    Walk On   

                                               Artist     Main Artist  \
0                           Rapsody Featuring Hit-Boy         Rapsody   
1                                           boygenius       Boygenius   
2                                         Jon Batiste     Jon Batiste   
3                                         Jon Batiste     Jon Batiste   
4                                        Lana Del Rey    Lana Del Rey   
5   Killer Mike Featuring André 3000, Future And E...     Killer Mike   
6                     Brandi Carlile Featuring Lucius  Brandi Carlile   
7                                                ABBA            Abba   
8                                        Bonnie Raitt    Bonnie Raitt   
9                                      Brandi Carlile  Brandi Carlile   
10                           Tony Bennett & Lady Gaga    Tony Bennett   
11                                        Jon Batiste     Jon Batiste   
12                                               ABBA            Abba   
13            

scrap the rest fo the data for these songs.

In [10]:
import time
album=[]
duration=[]
feats=[]
found=[]
i=0
for idx, row in extra_songs_df.iterrows():
  i+=1
  print(i)
  song_name = row["Cleaned Title"]
  artist_name=row["Main Artist"]
  results = sp.search(q=f"track:{song_name} artist:{artist_name}", limit=1, type='track')
  if idx%2==0: time.sleep(0.2) #to avoid too many request per second
  Flag=1
  # Extract relevant details
  if(len(results['tracks']['items'])==0):
    print("Song not found", row )

    print("-"*10)
    Flag=0
  else: track = results['tracks']['items'][0]

  found.append(Flag) #0 if not found else 1
  album.append(track['album']['name'] if Flag else None)
  duration.append(track['duration_ms']/1000 if Flag else None)
  if Flag:
    all_artists=[artist["name"] for artist in track["artists"]]
    if len(all_artists)==1: feats.append(None) #if theres only one artist, then there is no feat
    else: feats.append(','.join(all_artists[1:])) #store the feats only, not the main artist
  else: feats.append(None)



1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42


In [11]:
print(len(album)) #should be 42
print(len(duration))
print(len(feats))
print(len(found))

42
42
42
42


In [18]:
extra_songs_df['Album']=album
extra_songs_df['Duration']=duration
extra_songs_df['Album']=album
extra_songs_df['Spotify Featured Artists']=feats
extra_songs_df['Spotify Found']=found
extra_songs_df#42x23

Song ID                      Title              Cleaned Title  \
0       NaN                  Asteroids                  Asteroids   
1       NaN          Not Strong Enough          Not Strong Enough   
2       NaN                    Worship                    Worship   
3       NaN                  Butterfly                  Butterfly   
4       NaN                        A&W                        A&W   
5       NaN     SCIENTISTS & ENGINEERS     Scientists & Engineers   
6       NaN     You And Me On The Rock     You And Me On The Rock   
7       NaN         Don't Shut Me Down         Don'T Shut Me Down   
8       NaN             Just Like That             Just Like That   
9       NaN              Right On Time              Right On Time   
10      NaN    I Get A Kick Out Of You    I Get A Kick Out Of You   
11      NaN                    Freedom                    Freedom   
12      NaN  I Still Have Faith In You  I Still Have Faith In You   
13      NaN              Right On Time              Right On Time   
14      NaN              Fight For You              Fight For You   
15      NaN          A Beautiful Noise          A Beautiful Noise   
16      NaN                 Bath Salts                 Bath Salts   
17      NaN                     Colors                     Colors   
18      NaN            I Can't Breathe            I Can'T Breathe   
19      NaN                 Hard Place                 Hard Place   
20      NaN                    Hey, Ma                     Hey Ma   
21      NaN    Norman F***ing Rockwell    Norman Fucking Rockwell   
22      NaN                 Hard Place                 Hard Place   
23      NaN       Bring My Flowers Now       Bring My Flowers Now   
24      NaN                   Bad Idea                   Bad Idea   
25      NaN                   The Joke                   The Joke   
26      NaN                   The Joke                   The Joke   
27      NaN                        Win                        Win   
28      NaN                King's Dead                King'S Dead   
29      NaN                      Sassy                      Sassy   
30      NaN                   Chase Me                   Chase Me   
31      NaN                Really Love                Really Love   
32      NaN           F***in' Problems           Fuckin' Problems   
33      NaN                  Daughters                  Daughters   
34      NaN                   Holocene                   Holocene   
35      NaN                   Holocene                   Holocene   
36      NaN        Beg Steal Or Borrow        Beg Steal Or Borrow   
37      NaN     Please Read The Letter     Please Read The Letter   
38      NaN            Sexual Eruption            Sexual Eruption   
39      NaN           Here We Go Again           Here We Go Again   
40      NaN      Keep Me In Your Heart      Keep Me In Your Heart   
41      NaN                    Walk On                    Walk On   

                                               Artist     Main Artist  \
0                           Rapsody Featuring Hit-Boy         Rapsody   
1                                           boygenius       Boygenius   
2                                         Jon Batiste     Jon Batiste   
3                                         Jon Batiste     Jon Batiste   
4                                        Lana Del Rey    Lana Del Rey   
5   Killer Mike Featuring André 3000, Future And E...     Killer Mike   
6                     Brandi Carlile Featuring Lucius  Brandi Carlile   
7                                                ABBA            Abba   
8                                        Bonnie Raitt    Bonnie Raitt   
9                                      Brandi Carlile  Brandi Carlile   
10                           Tony Bennett & Lady Gaga    Tony Bennett   
11                                        Jon Batiste     Jon Batiste   
12                                               ABBA            Abba   
13            

In [ ]:
# temp= extra_songs_df.drop(["Song Writers/Credits","Producer","Label", "Genius Found", "Lyrics", "Genius Album", "Release Date"], axis=1)
# temp

###lyrics ovh search

In [26]:
import time
i=0
lyrics_all=[]
for idx, row in extra_songs_df.iterrows():
  i+=1
  print(i)
  song_name = row["Cleaned Title"]
  artist_name=row["Main Artist"]
  # idx%2==0: time.sleep(0.2) #slow down
  lyrics=get_lyrics(song_name, artist_name)
  if lyrics==None: print("Couln't find lyric for: ", artist_name, song_name)
  lyrics_all.append(lyrics)

print(len(lyrics_all))
extra_songs_df["Lyrics"]=lyrics_all


1
2
3
4
5
Couln't find lyric for:  Lana Del Rey A&W
6
Couln't find lyric for:  Killer Mike Scientists & Engineers
7
8
9
Couln't find lyric for:  Bonnie Raitt Just Like That
10
11
Couln't find lyric for:  Tony Bennett I Get A Kick Out Of You
12
13
14
15
Couln't find lyric for:  H.E.R. Fight For You
16
17
18
19
Couln't find lyric for:  H.E.R. I Can'T Breathe
20
Couln't find lyric for:  H.E.R. Hard Place
21
22
23
Couln't find lyric for:  H.E.R. Hard Place
24
25
Couln't find lyric for:  Ybn Cordae Bad Idea
26
27
28
29
30
31
Couln't find lyric for:  Danger Mouse Chase Me
32
33
34
35
36
37
38
39
40
41
42
42


## genius data

In [32]:
import requests


def search_song_GENIUS(song_name, artist_name):
    base_url = "https://api.genius.com/search"
    query = f"{song_name} {artist_name}"
    response = requests.get(base_url, params={'q': query}, headers=headers)

    if response.status_code != 200:
        print("Failed to search Genius")
        return None, None

    results = response.json()['response']['hits']
    for hit in results:
        if artist_name.lower() in hit['result']['primary_artist']['name'].lower():
            url = hit['result']['url']
            song_id = hit['result']['id']
            return url, song_id

    return None, None


In [30]:
def get_song_album(song_id):
    song_url = f"https://api.genius.com/songs/{song_id}"
    response = requests.get(song_url, headers=headers)

    if response.status_code != 200:
        return None

    song_info = response.json()['response']['song']
    album = song_info.get('album')
    return album['name'] if album else None


In [31]:
def get_song_date(song_id):
    song_url = f"https://api.genius.com/songs/{song_id}"
    response = requests.get(song_url, headers=headers)

    if response.status_code != 200:
        return None

    song_info = response.json()['response']['song']
    return song_info.get('release_date', None)


In [33]:
import time
i=0
genius_found=[]
release_date=[]
album_genius=[]
for idx, row in extra_songs_df.iterrows():
  i+=1
  print(i)
  song_name = row["Cleaned Title"]
  artist_name=row["Main Artist"]
  url, id= search_song_GENIUS(song_name, artist_name)
  # if idx%2==0: time.sleep(0.2) #to avoid too many request per second
  Flag=1
  # Extract relevant details
  if(id==None):
    print("Song not found", row )

    print("-"*10)
    Flag=0
  else:  #song was found
    date= get_song_date(id)
    #extract album name of the data if it wasnt found on spotify
    if row["Spotify Found"]=='0' and row['Album']=="":
      print("Genius Found, but spotify didn't. Search for Album of:", song_name," by ", artist_name)
      album= get_song_album(id)
    else: album=None

  genius_found.append(Flag) #0 if not found else 1
  release_date.append(date if Flag else None)
  album_genius.append(album if Flag else None )

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
Song not found Song ID                                                        NaN
Title                                                     Bad Idea
Cleaned Title                                             Bad Idea
Artist                      YBN Cordae Featuring Chance The Rapper
Main Artist                                             Ybn Cordae
Feat                                             Chance The Rapper
Song Writers/Credits                                           NaN
Producer                                                       NaN
Label                                                          NaN
Album                                                 The Lost Boy
Duration                                                   234.614
Spotify Featured Artists                         Chance the Rapper
Spotify Found                                                    1
Release Date                                    

In [34]:
print(len(genius_found)) #42
print(len(release_date))
print(len(album_genius))


42
42
42


In [35]:
extra_songs_df['Genius Album']=album_genius
extra_songs_df['Release Date']=release_date
extra_songs_df['Genius Found']=genius_found

In [36]:
extra_songs_df

Song ID                      Title              Cleaned Title  \
0       NaN                  Asteroids                  Asteroids   
1       NaN          Not Strong Enough          Not Strong Enough   
2       NaN                    Worship                    Worship   
3       NaN                  Butterfly                  Butterfly   
4       NaN                        A&W                        A&W   
5       NaN     SCIENTISTS & ENGINEERS     Scientists & Engineers   
6       NaN     You And Me On The Rock     You And Me On The Rock   
7       NaN         Don't Shut Me Down         Don'T Shut Me Down   
8       NaN             Just Like That             Just Like That   
9       NaN              Right On Time              Right On Time   
10      NaN    I Get A Kick Out Of You    I Get A Kick Out Of You   
11      NaN                    Freedom                    Freedom   
12      NaN  I Still Have Faith In You  I Still Have Faith In You   
13      NaN              Right On Time              Right On Time   
14      NaN              Fight For You              Fight For You   
15      NaN          A Beautiful Noise          A Beautiful Noise   
16      NaN                 Bath Salts                 Bath Salts   
17      NaN                     Colors                     Colors   
18      NaN            I Can't Breathe            I Can'T Breathe   
19      NaN                 Hard Place                 Hard Place   
20      NaN                    Hey, Ma                     Hey Ma   
21      NaN    Norman F***ing Rockwell    Norman Fucking Rockwell   
22      NaN                 Hard Place                 Hard Place   
23      NaN       Bring My Flowers Now       Bring My Flowers Now   
24      NaN                   Bad Idea                   Bad Idea   
25      NaN                   The Joke                   The Joke   
26      NaN                   The Joke                   The Joke   
27      NaN                        Win                        Win   
28      NaN                King's Dead                King'S Dead   
29      NaN                      Sassy                      Sassy   
30      NaN                   Chase Me                   Chase Me   
31      NaN                Really Love                Really Love   
32      NaN           F***in' Problems           Fuckin' Problems   
33      NaN                  Daughters                  Daughters   
34      NaN                   Holocene                   Holocene   
35      NaN                   Holocene                   Holocene   
36      NaN        Beg Steal Or Borrow        Beg Steal Or Borrow   
37      NaN     Please Read The Letter     Please Read The Letter   
38      NaN            Sexual Eruption            Sexual Eruption   
39      NaN           Here We Go Again           Here We Go Again   
40      NaN      Keep Me In Your Heart      Keep Me In Your Heart   
41      NaN                    Walk On                    Walk On   

                                               Artist     Main Artist  \
0                           Rapsody Featuring Hit-Boy         Rapsody   
1                                           boygenius       Boygenius   
2                                         Jon Batiste     Jon Batiste   
3                                         Jon Batiste     Jon Batiste   
4                                        Lana Del Rey    Lana Del Rey   
5   Killer Mike Featuring André 3000, Future And E...     Killer Mike   
6                     Brandi Carlile Featuring Lucius  Brandi Carlile   
7                                                ABBA            Abba   
8                                        Bonnie Raitt    Bonnie Raitt   
9                                      Brandi Carlile  Brandi Carlile   
10                           Tony Bennett & Lady Gaga    Tony Bennett   
11                                        Jon Batiste     Jon Batiste   
12                                               ABBA            Abba   
13            

In [37]:
extra_songs_df=extra_songs_df.drop_duplicates()
extra_songs_df #38 x 22

Song ID                      Title              Cleaned Title  \
0       NaN                  Asteroids                  Asteroids   
1       NaN          Not Strong Enough          Not Strong Enough   
2       NaN                    Worship                    Worship   
3       NaN                  Butterfly                  Butterfly   
4       NaN                        A&W                        A&W   
5       NaN     SCIENTISTS & ENGINEERS     Scientists & Engineers   
6       NaN     You And Me On The Rock     You And Me On The Rock   
7       NaN         Don't Shut Me Down         Don'T Shut Me Down   
8       NaN             Just Like That             Just Like That   
9       NaN              Right On Time              Right On Time   
10      NaN    I Get A Kick Out Of You    I Get A Kick Out Of You   
11      NaN                    Freedom                    Freedom   
12      NaN  I Still Have Faith In You  I Still Have Faith In You   
14      NaN              Fight For You              Fight For You   
15      NaN          A Beautiful Noise          A Beautiful Noise   
16      NaN                 Bath Salts                 Bath Salts   
17      NaN                     Colors                     Colors   
18      NaN            I Can't Breathe            I Can'T Breathe   
19      NaN                 Hard Place                 Hard Place   
20      NaN                    Hey, Ma                     Hey Ma   
21      NaN    Norman F***ing Rockwell    Norman Fucking Rockwell   
23      NaN       Bring My Flowers Now       Bring My Flowers Now   
24      NaN                   Bad Idea                   Bad Idea   
25      NaN                   The Joke                   The Joke   
27      NaN                        Win                        Win   
28      NaN                King's Dead                King'S Dead   
29      NaN                      Sassy                      Sassy   
30      NaN                   Chase Me                   Chase Me   
31      NaN                Really Love                Really Love   
32      NaN           F***in' Problems           Fuckin' Problems   
33      NaN                  Daughters                  Daughters   
34      NaN                   Holocene                   Holocene   
36      NaN        Beg Steal Or Borrow        Beg Steal Or Borrow   
37      NaN     Please Read The Letter     Please Read The Letter   
38      NaN            Sexual Eruption            Sexual Eruption   
39      NaN           Here We Go Again           Here We Go Again   
40      NaN      Keep Me In Your Heart      Keep Me In Your Heart   
41      NaN                    Walk On                    Walk On   

                                               Artist     Main Artist  \
0                           Rapsody Featuring Hit-Boy         Rapsody   
1                                           boygenius       Boygenius   
2                                         Jon Batiste     Jon Batiste   
3                                         Jon Batiste     Jon Batiste   
4                                        Lana Del Rey    Lana Del Rey   
5   Killer Mike Featuring André 3000, Future And E...     Killer Mike   
6                     Brandi Carlile Featuring Lucius  Brandi Carlile   
7                                                ABBA            Abba   
8                                        Bonnie Raitt    Bonnie Raitt   
9                                      Brandi Carlile  Brandi Carlile   
10                           Tony Bennett & Lady Gaga    Tony Bennett   
11                                        Jon Batiste     Jon Batiste   
12                                               ABBA            Abba   
14                                             H.E.R.          H.E.R.   
15                       Alicia Keys & Brandi Carlile     Alicia Keys   
16                          DMX Featuring Jay-Z & Nas             Dmx   
17                                        Black Pumas     Black Pumas  

In [38]:
extra_songs_df.to_csv("cleaned_missing_songs_grammy_dwi.csv")

perfect now we have the df with the extra songs and all the needed info. all we need to do is to add them to our OG df. Before that we will go get the artist ID.
